---
title: "Figure0_Scenarios"
output: html_document
date: "2024-07-17"
editor_options: 
  chunk_output_type: console
---

```{r library}


library(ggplot2)
library(tidyr)
library(dplyr)
library(reshape2)
library(ggpubr)
library(socialmixr)
library("RColorBrewer")
library(rmarkdown)
library(plotly)
library(demodelr)
library(forcats)
library(ggh4x)
library(lemon)
library(ggthemes)
library(khroma)
library(extrafont)
library(here)


```


#Part 1 of figure 1

```{r setup}

#Odin equations 
path <- here::here("Script", "DeuxAgeHuitResistanceDeuxAntibiosOdin.R")
code <- paste(readLines(path, warn = FALSE), collapse = "\n")
gen <- odin::odin(code)

#Donnes 2021 otites pour penicillines: 
d2=0.075/0.53; d3=0.075/0.53; d4=0.085/0.53; d5=0.09/0.53; d6=0.12/0.53; d7=0.075/0.53; d8=0.01/0.53 
Rcr=0.58; Rmacro=0.28; Ramox=0.43; pi=0.52
ConsoAmox=0.95; ConsoMacro=0.083;Lambda=1/43
InvasionRate=4.8*10**(-7)
DDJAmox=1.5 #ref 1.5 DDD according to OMS for amoxicillin
DDJMacro=2 #ref 2 DDD according to OMS fot pristinamycin

```

```{r lancement et reduction pour la figure 1a}

LancementEffetScenario <- function(z,time){
    Rcr=z[1]
    Ramox=z[2]
    Rmacro=z[3]
    ConsoAmox=z[4]
    ConsoMacro=z[5]
    df<-data_frame()
   for (k in 1:4){
     #Scenario 1 : amoxicillin exposure rate reduction
    if(k==1){ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(7,7,7,7)
    ReductionFreq=c(1,0.75,0.5,0.25)
    AugmentationFreq=c(0,0,0,0)
    ReductionDoseRefAmox=c(1,1,1,1)
    A=matrix(c(0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)
    }
     #Scenario 2 : amoxicillin treatment duration reduction
    if(k==2){ ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0, #Reduction de l'efficacité du traitement
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(7,5.25,3.5,1.75)
    ReductionFreq=c(1,1,1,1)
    AugmentationFreq=c(0,0,0,0)
    ReductionDoseRefAmox=c(1,1,1,1)
    A=matrix(c(0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)
    }
    #Scenario 3 : amoxicillin dose/day reduction
    if(k==3){ ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.06,0,0,0,0,0,
          1,0.47,0,0,0,0,0,0,
          1,0.06,0,0,0,0,0,0),ncol=4)
    ReductionDuree=c(7,7,7,7)
    ReductionFreq=c(1,1,1,1)
    AugmentationFreq=c(0,0,0,0)
    ReductionDoseRefAmox=c(1,0.75,0.5,0.25)
    A=matrix(c(0,0,0,1,1,1,1,1,
               0,0,1,1,1,1,1,1,
               0,0,1,1,1,1,1,1,
               0,1,1,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)
    }
    #Scenario 4 : switching from amoxicillin to macrolides
    if(k==4){ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(7,7,7,7)
    ReductionFreq=c(1,0.75,0.5,0.25)
    AugmentationFreq=c(0,0.25,0.5,0.75)
    ReductionDoseRefAmox=c(1,1,1,1)
    A=matrix(c(0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)}
    for(j in 1:4){
      print(((ConsoMacro*(1+((ConsoAmox)/(ConsoMacro))*AugmentationFreq[j]))))
      mod <- gen$new( US_0=c((70000000*(1-(0.0163+0.0016)))*(1-pi)*0.055),
                  UCm1_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  UCm1_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*(Rmacro-Rcr*Ramox)*0.055),
                  UCm2_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d2*0.055),
                  UCm2_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d2*0.055),
                  UCm3_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d3*0.055),
                  UCm3_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d3*0.055),
                  UCm4_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d4*0.055),
                  UCm4_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d4*0.055),
                  UCm5_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d5*0.055),
                  UCm5_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d5*0.055),
                  UCm6_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d6*0.055),
                  UCm6_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d6*0.055),
                  UCm7_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d7*0.055),
                  UCm7_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d7*0.055),
                  UCm8_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d8*0.055),
                  UCm8_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d8*0.055),
                  
                  AES_0=c((70000000*0.0163)*(1-pi)*0.055),
                  AECm1_S_0=c((70000000*0.0163)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  AECm1_R_0=c((70000000*0.0163)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  AECm2_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d2*0.055),
                  AECm2_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d2*0.055),
                  AECm3_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d3*0.055),
                  AECm3_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d3*0.055),
                  AECm4_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d4*0.055),
                  AECm4_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d4*0.055),
                  AECm5_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d5*0.055),
                  AECm5_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d5*0.055),
                  AECm6_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d6*0.055),
                  AECm6_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d6*0.055),
                  AECm7_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d7*0.055),
                  AECm7_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d7*0.055),
                  AECm8_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d8*0.055),
                  AECm8_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d8*0.055),
                  
                  MES_0=c((70000000*0.0016)*(1-pi)*0.055),
                  MECm1_S_0=c((70000000*0.0016)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  MECm1_R_0=c((70000000*0.0016)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  MECm2_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d2*0.055),
                  MECm2_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d2*0.055),
                  MECm3_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d3*0.055),
                  MECm3_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d3*0.055),
                  MECm4_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d4*0.055),
                  MECm4_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d4*0.055),
                  MECm5_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d5*0.055),
                  MECm5_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d5*0.055),
                  MECm6_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d6*0.055),
                  MECm6_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d6*0.055),
                  MECm7_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d7*0.055),
                  MECm7_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d7*0.055),
                  MECm8_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d8*0.055),
                  MECm8_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d8*0.055),
                      
                  # Dose1=1 sigmoid 0.08 calibrés pr equilibre Rcr=0.58 Rmacro=0.28 Ramox=0.43
                  fA1=1, fA2=0.9999748 , fA3=0.9916096 , fA4=0.9420954 , fA5=0.9192299 , fA6=0.9192278 , fA7=0.9192375 , fA8=0.9194097 ,
                  fMS=1,fMR=0.9938509 , #macrolide fitness cost
                  a1=A[j,1],a2=A[j,2],a3=A[j,3],a4=A[j,4],a5=A[j,5],a6=A[j,6],a7=A[j,7],a8=A[j,8], #possibilité de transmissibilité quand exposé au traitement suivant la dose administrée
                  #V=c(Vopti),
                  V=c(0.0559375),
                      
                  Beta=matrix(c(1),nrow = 1, ncol = 1,byrow = TRUE),
                  
                  #Consommation normale observée adultes 
                  Phi_A=c(ConsoAmox*ReductionFreq[j]/(365)),
                  Phi_M=c((ConsoMacro*(1+((ConsoAmox)/(ConsoMacro))*AugmentationFreq[j]))/365),
                      
                  Mu=c(0),
                  mu0=0,
                  Lambda=c(Lambda),
                  gamma_A=1/ReductionDuree[j],
                  gamma_M=1/7,
                      
                  #Dose 500mg, q8h
                  dose1_A=ReductionDose[1,j],
                  dose2_A=ReductionDose[2,j],
                  dose3_A=ReductionDose[3,j],
                  dose4_A=ReductionDose[4,j],
                  dose5_A=ReductionDose[5,j],
                  dose6_A=ReductionDose[6,j],
                  dose7_A=ReductionDose[7,j],
                  dose8_A=ReductionDose[8,j],
                  dose1_M= 1.006924, #500mg,q12h MIC=0.06
                  dose2_M=0.03449561,#500mg,q12h MIC=0.125
                  
                  theta=0.5,
                  N_age=1)
      
      t <- seq(0, time,1)
      y_odin <- mod$run(t)
      out_odin <- as.data.frame(y_odin)
      out_odin = out_odin %>%
        mutate(
          `t`=`t`,
          `Pen_S[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`,
          `Pen_I[1]`=`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`,
          `Pen_R[1]`=`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          `Macro_S[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`,
          `Macro_R[1]`=`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
         
          `CmNsR[1]`=`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          `Totcarrier[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          `Tot[1]`=`US[1]`+`AES[1]`+`MES[1]`+`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          `Amox[1]`=`AES[1]`+`AECm1_S[1]`+`AECm1_R[1]`+`AECm2_S[1]`+`AECm2_R[1]`+`AECm3_S[1]`+`AECm3_R[1]`+`AECm4_S[1]`+`AECm4_R[1]`+`AECm5_S[1]`+`AECm5_R[1]`+`AECm6_S[1]`+`AECm6_R[1]`+`AECm7_S[1]`+`AECm7_R[1]`+`AECm8_S[1]`+`AECm8_R[1]`,
          
          `Macro[1]`=`MES[1]`+`MECm1_S[1]`+`MECm1_R[1]`+`MECm2_S[1]`+`MECm2_R[1]`+`MECm3_S[1]`+`MECm3_R[1]`+`MECm4_S[1]`+`MECm4_R[1]`+`MECm5_S[1]`+`MECm5_R[1]`+`MECm6_S[1]`+`MECm6_R[1]`+`MECm7_S[1]`+`MECm7_R[1]`+`MECm8_S[1]`+`MECm8_R[1]`,
          
          `AmoxInst[1]`=(ConsoAmox*ReductionFreq[j]/(365))*(`US[1]`+`UCm1_S[1]`+`UCm1_R[1]`+`UCm2_S[1]`+`UCm2_R[1]`+`UCm3_S[1]`+`UCm3_R[1]`+`UCm4_S[1]`+`UCm4_R[1]`+`UCm5_S[1]`+`UCm5_R[1]`+`UCm6_S[1]`+`UCm6_R[1]`+`UCm7_S[1]`+`UCm7_R[1]`+`UCm8_S[1]`+`UCm8_R[1]`),
          
          `MacroInst[1]`=((ConsoMacro*(1+((ConsoAmox)/(ConsoMacro))*AugmentationFreq[j]))/365)*(`US[1]`+`UCm1_S[1]`+`UCm1_R[1]`+`UCm2_S[1]`+`UCm2_R[1]`+`UCm3_S[1]`+`UCm3_R[1]`+`UCm4_S[1]`+`UCm4_R[1]`+`UCm5_S[1]`+`UCm5_R[1]`+`UCm6_S[1]`+`UCm6_R[1]`+`UCm7_S[1]`+`UCm7_R[1]`+`UCm8_S[1]`+`UCm8_R[1]`),
          
          `Rcr`=`Rcr`,
          .keep = "none"
        )
      out_odin = out_odin %>%
        mutate(
          `t`=`t`,
          `Amoxicilline_Phi`=`Amox[1]`*1000/(70000000*0.055),
          `Amoxicilline_DDJ`=(`Amox[1]`*3*1*ReductionDoseRefAmox[j]*1000)/(DDJAmox*70000000*0.055), #3*1g =3g de prise journalière par personne
          `Amoxicilline_Inst`=(`AmoxInst[1]`*1000)/(DDJAmox*70000000*0.055),
          `Macrolide_Phi`=`Macro[1]`*1000/(70000000*0.055),
          `Macrolide_DDJ`=(`Macro[1]`*2*1*1000)/(DDJMacro*70000000*0.055),#2*1g =2g de prise journalière par personne
          `Macrolide_Inst`=(`MacroInst[1]`*1000)/(70000000*0.055),
          #`Rcr`=`Rcr`,
          .keep = "none"
        )
      out_odin$Reduction<-j
      out_odin$Scenario<-k
      df<-rbind(df,out_odin)
      }
   }
  return(df)
  
}

df<-LancementEffetScenario(c(Rcr,Ramox,Rmacro,ConsoAmox,ConsoMacro),100)

```

```{r datframe delay }

df<-LancementEffetScenario(c(Rcr,Ramox,Rmacro,ConsoAmox,ConsoMacro),100)
df_beforeshortage<- subset(df, Reduction %in% c("1"))
df<-LancementEffetScenario(c(Rcr,Ramox,Rmacro,ConsoAmox,ConsoMacro),365)
df_shortage<- subset(df, Reduction %in% c("3"))
df_shortage <- df_shortage %>%
  mutate(t = t + 100)

df<-rbind(df_beforeshortage,df_shortage)

```


```{r ggplot evolution Figure 1}

#df<- subset(df, Reduction %in% c("1"))

out_long= df %>% pivot_longer(
  cols = `Amoxicilline_Phi`:`Macrolide_Inst`,
  names_to = c("Antibiotique","Compartment"),
  names_pattern = "([A-Za-z0-9]+)_(.+)",
  values_to = "count"
)


labeller_fig1=labeller(Scenario=c("1"="","2"="","3"="","4"=""))

# Ouvrir un périphérique graphique pour sauvegarder le plot en tant qu'image PNG
p<-ggplot(out_long,aes(x=t,y=count,colour=Antibiotique,linetype=as.factor(Compartment)))+
  geom_rect(aes(xmin =100, xmax = Inf, ymin = -Inf, ymax = Inf),fill = "#FFE4E1", alpha = 0.04,inherit.aes = FALSE)+
  #geom_text(data = dplyr::filter(out_long,t==0|t==465),aes(label = round(count, 2)),vjust = -0.5, hjust = 0.5,show.legend = FALSE) +
  geom_line(linewidth=1.5)+
  scale_linetype_manual(name = "Outcome",values = c( "Phi" = "solid", "DDJ" = "dotted","Inst" = "dashed"),labels = c("Phi"="Exposed prevalence/1,000 children","DDJ"= "Number of DDD/1,000 children/d","Inst"="Exposed incidence/1,000 children/d")) +
  scale_color_manual(values=c(Amoxicilline="orange",Macrolide="purple" ),name = "Antibiotic", labels = c("Beta-lactam", "Macrolide"))+
  xlab("Time (days)")+ggtitle("Antibiotic exposure")+
  scale_y_continuous(
    name = "",
    #sec.axis = sec_axis(~ . / 1, name = "")  # Divise par 10000 pour revenir à l'échelle originale de prop_am
  ) +
  facet_wrap(~Scenario, ncol=1,labeller =labeller_fig1,scales = "free" )+
  theme_clean()+
  theme(legend.background = element_rect(fill = "white", colour = "black"),legend.key.width =unit(2, "cm"),
        legend.title=element_text(size = 22),legend.text=element_text(size = 20),
        legend.direction = "vertical",legend.box = "horizontal", legend.box.just = "center",legend.position = "bottom",
        axis.text = element_text(size =20),axis.title = element_text(size = 26),
        plot.title = element_text(size = 26, face = "bold",hjust = 0.5,margin = margin(b = -15)),
        panel.border = element_blank() ,plot.background = element_blank())+
    guides(
    color = guide_legend(order = 1),
    linetype = guide_legend(order = 2)
  )


png(filename = here::here("Figures", "Figure1a.png"), width = 500, height = 1200)
p
dev.off()

```



#Part 2 of figure 2

```{r ggplot barplot Figure 1 with Rcr=0.58 with error of incertitude bar}

dfnew <- read.csv(here::here("Files", "fichierCombine070225_figure1.csv"))
df<-dfnew
df<-subset(df, select = -X)

out_long= df %>% pivot_longer(
  cols = `Pen_S`:`Cross_T`,
  names_to = c("Antibiotique","Compartment"),
  names_pattern = "([A-Za-z0-9]+)_(.)",
  values_to = "count"
)
out_long <- subset(out_long, Antibiotique %in% c("Pen","Macro","Multi"))

out_long <- subset(out_long, Reduction %in% c("3"))
out_long <- subset(out_long, select=-Reduction)
out_long <- subset(out_long, select=-Rcr)

out_long$Compartment <- factor(out_long$Compartment, levels = c("S", "I", "R"))
out_long$Antibiotique <- factor(out_long$Antibiotique, levels = c("Pen", "Macro", "Multi"))

out_long<-as.data.frame(out_long)
out_long$t <- as.factor(out_long$t)

# Calculer les statistiques pour les lignes à 0% de réduction
summary_stats <- out_long %>% 
  group_by(t,Scenario,Antibiotique,Compartment) %>%
  summarize(
    mean_value = median(count),
    q1_value = quantile(count, 0.25),
    q3_value = quantile(count, 0.75),
    min=min(count),
    max=max(count)
  )

summary_stats$mean_value <- as.numeric(summary_stats$mean_value)

labeller_fig1=labeller(Scenario=c("1"="S1","2"="S2","3"="S3","4"="S4"), Antibiotique=c("Pen"="Penicillin ","Macro"="Macrolide ","Multi"="Multidrug"))


p<-ggplot(summary_stats, aes(x = Compartment, y = mean_value, fill = Compartment, alpha = factor(t))) +
  geom_col(position = position_dodge(), color = "black") +
  scale_fill_manual(
    name = "Antibiotic sensitivity level",
    values = c("S" = "#32CD32",  # Vert pour S
               "I" = "#FFD700",  # Jaune pour I
               "R" = "#FF6347"),  # Rouge pour R
    labels = c("Susceptible", "Intermediate","Resistant")
  ) +
  scale_alpha_manual(
    values = c(1.1, 0.4),  # Plus clair pour t=0, plus clair pour t=365
    name = "Time",
    labels = c("Before shortage", "1-year shortage")
  ) +
  coord_cartesian(ylim = c(0, 0.85)) +
  geom_errorbar(data = dplyr::filter(summary_stats,t==0), aes(ymin=min, ymax=max), position=position_nudge(x=-0.1),width = 0.2)+
  geom_errorbar(data = dplyr::filter(summary_stats,t==365), aes(ymin=min, ymax=max), position=position_nudge(x=0.25),width = 0.2)+
  geom_text(aes(label=round(mean_value,2)),vjust=-1,position = position_dodge(0.9),show.legend = FALSE,size=7,face = "bold")+
  xlab("Sensitivity level in colonized")+ylab("Proportion")+
  facet_rep_grid(Scenario~Antibiotique, labeller = labeller_fig1,scales="free")+
  theme_clean()+
  theme(legend.background = element_rect(fill = "white", colour = "black"),legend.key.width =unit(1.4, "cm"),
        legend.title=element_text(size = 22),legend.text=element_text(size = 20),
        legend.direction = "vertical",legend.box = "horizontal", legend.box.just = "center",legend.position = "bottom",
        axis.text = element_text(size =20),axis.title = element_text(size = 28),
        strip.text = element_text(size = 25, face = "bold",hjust = 0.5),strip.placement = "outside",
        panel.border = element_blank() ,plot.background = element_blank())


png(filename = here::here("Figures", "Figure1b_test.png"), width = 1200, height = 1200)
p
dev.off()



```


```{r evolution figure 1 observées avec IC }

dfnew <- read.csv(here::here("Files", "fichierCombine070225_figure1.csv"))
df<-dfnew
df<-subset(df, select = -X)

out_long= df %>% pivot_longer(
  cols = `Pen_S`:`Cross_T`,
  names_to = c("Antibiotique","Compartment"),
  names_pattern = "([A-Za-z0-9]+)_(.)",
  values_to = "count"
)
out_long <- subset(out_long, Antibiotique %in% c("Pen","Macro","Multi"))

out_long <- subset(out_long, Reduction %in% c("3"))
out_long <- subset(out_long, select=-Reduction)
out_long <- subset(out_long, select=-Rcr)

out_long$Compartment <- factor(out_long$Compartment, levels = c("S", "I", "R"))
out_long$Antibiotique <- factor(out_long$Antibiotique, levels = c("Pen", "Macro", "Multi"))

out_long<-as.data.frame(out_long)
out_long$t <- as.factor(out_long$t)

# Calculer les statistiques pour les lignes à 0% de réduction
out_long <- out_long %>% 
  group_by(t,Scenario,Antibiotique,Compartment) %>%
  summarize(
    median_value = median(count),
    min=min(count),
    max=max(count)
  )

# Séparer les données en deux DataFrames
df_t0 <- out_long %>% filter(t == 0)
df_t365 <- out_long %>% filter(t == 365)

# Renommer les colonnes de df_t365 pour pouvoir faire la jointure
df_t365 <- df_t365 %>%rename(median_value_365 = median_value)
df_t365 <- df_t365 %>%rename(min_365 = min)
df_t365 <- df_t365 %>%rename(max_365 = max)

# Faire la jointure sur les colonnes de paramètres
merged_df <- df_t0 %>%inner_join(df_t365, by = c( "Scenario", "Antibiotique", "Compartment"))

# Calculer la variation
merged_df <- merged_df %>%
  mutate(Variation_Median = ((median_value_365 - median_value) * 100) / median_value) %>%
  mutate(Variation_Min= ((min_365 - min) * 100) / min) %>%
  mutate(Variation_Max = ((max_365 - max) * 100) / max) %>%
  select(Scenario, Antibiotique, Compartment, Variation_Median,Variation_Min, Variation_Max)

# Afficher le résultat
print(merged_df)

```

##Suplementary figure 1

```{r lancement et reduction pour la figure 1}

LancementReduction <- function(z,time){
    Rcr=z[1]
    Ramox=z[2]
    Rmacro=z[3]
    ConsoAmox=z[4]
    ConsoMacro=z[5]
    #Vopti=as.numeric((Optim_vi=optim(c(0.01),OptimVi,z=z,M=M,control = list(maxit = 20000)))$par)
    #cat(Rcr, " ", Ramox," ",Rmacro, " ",ConsoAmox," ",ConsoMacro," " ,Vopti,"\n")
    df<-data_frame()
   for (k in 1:4){
     #print(k)
     if(k==1){ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(7,7,7,7)
    ReductionFreq=c(1,0.75,0.5,0.25)
    AugmentationFreq=c(0,0,0,0)
    A=matrix(c(0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)
    }
     if(k==2){ ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(7,5.25,3.5,1.75)
    ReductionFreq=c(1,1,1,1)
    AugmentationFreq=c(0,0,0,0)
    A=matrix(c(0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)
    }
    if(k==3){ ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.06,0,0,0,0,0,
          1,0.47,0,0,0,0,0,0,
          1,0.06,0,0,0,0,0,0),ncol=4)
    ReductionDuree=c(7,7,7,7)
    ReductionFreq=c(1,1,1,1)
    AugmentationFreq=c(0,0,0,0)
    A=matrix(c(0,0,0,1,1,1,1,1,
               0,0,1,1,1,1,1,1,
               0,0,1,1,1,1,1,1,
               0,1,1,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)
    }
    if(k==4){ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(7,7,7,7)
    ReductionFreq=c(1,0.75,0.5,0.25)
    AugmentationFreq=c(0,0.25,0.5,0.75)
    A=matrix(c(0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)}
    for(j in 1:4){
      #print(j)
      mod <- gen$new( US_0=c((70000000*(1-(0.0163+0.0016)))*(1-pi)*0.055),
                  UCm1_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  UCm1_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*(Rmacro-Rcr*Ramox)*0.055),
                  UCm2_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d2*0.055),
                  UCm2_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d2*0.055),
                  UCm3_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d3*0.055),
                  UCm3_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d3*0.055),
                  UCm4_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d4*0.055),
                  UCm4_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d4*0.055),
                  UCm5_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d5*0.055),
                  UCm5_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d5*0.055),
                  UCm6_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d6*0.055),
                  UCm6_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d6*0.055),
                  UCm7_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d7*0.055),
                  UCm7_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d7*0.055),
                  UCm8_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d8*0.055),
                  UCm8_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d8*0.055),
                  
                  AES_0=c((70000000*0.0163)*(1-pi)*0.055),
                  AECm1_S_0=c((70000000*0.0163)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  AECm1_R_0=c((70000000*0.0163)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  AECm2_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d2*0.055),
                  AECm2_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d2*0.055),
                  AECm3_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d3*0.055),
                  AECm3_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d3*0.055),
                  AECm4_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d4*0.055),
                  AECm4_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d4*0.055),
                  AECm5_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d5*0.055),
                  AECm5_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d5*0.055),
                  AECm6_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d6*0.055),
                  AECm6_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d6*0.055),
                  AECm7_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d7*0.055),
                  AECm7_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d7*0.055),
                  AECm8_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d8*0.055),
                  AECm8_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d8*0.055),
                  
                  MES_0=c((70000000*0.0016)*(1-pi)*0.055),
                  MECm1_S_0=c((70000000*0.0016)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  MECm1_R_0=c((70000000*0.0016)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  MECm2_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d2*0.055),
                  MECm2_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d2*0.055),
                  MECm3_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d3*0.055),
                  MECm3_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d3*0.055),
                  MECm4_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d4*0.055),
                  MECm4_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d4*0.055),
                  MECm5_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d5*0.055),
                  MECm5_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d5*0.055),
                  MECm6_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d6*0.055),
                  MECm6_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d6*0.055),
                  MECm7_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d7*0.055),
                  MECm7_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d7*0.055),
                  MECm8_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d8*0.055),
                  MECm8_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d8*0.055),
                      
                  # Dose1=1 sigmoid 0.08 calibrés pr equilibre Rcr=0.58 Rmacro=0.28 Ramox=0.43
                  fA1=1, fA2=0.9999748 , fA3=0.9916096 , fA4=0.9420954 , fA5=0.9192299 , fA6=0.9192278 , fA7=0.9192375 , fA8=0.9194097 ,
                  fMS=1,fMR=0.9938509 ,
                  a1=A[j,1],a2=A[j,2],a3=A[j,3],a4=A[j,4],a5=A[j,5],a6=A[j,6],a7=A[j,7],a8=A[j,8],
                  #V=c(Vopti),
                  V=c(0.0559375),
                      
                  Beta=matrix(c(1),nrow = 1, ncol = 1,byrow = TRUE),
                  
                  #Consommation normale observée adultes 
                  Phi_A=c(ConsoAmox*ReductionFreq[j]/(365)),
                  Phi_M=c((ConsoMacro*(1+((ConsoAmox)/(ConsoMacro))*AugmentationFreq[j]))/365),
                      
                  Mu=c(0),
                  mu0=0,
                  Lambda=c(Lambda),
                  gamma_A=1/ReductionDuree[j],
                  gamma_M=1/7,
                      
                  #Dose 500mg, q8h
                  dose1_A=ReductionDose[1,j],
                  dose2_A=ReductionDose[2,j],
                  dose3_A=ReductionDose[3,j],
                  dose4_A=ReductionDose[4,j],
                  dose5_A=ReductionDose[5,j],
                  dose6_A=ReductionDose[6,j],
                  dose7_A=ReductionDose[7,j],
                  dose8_A=ReductionDose[8,j],
                  dose1_M= 1.006924, #500mg,q12h MIC=0.06
                  dose2_M=0.03449561,#500mg,q12h MIC=0.125
                  
                  theta=0.5,
                  N_age=1)
      
      t <- seq(0, time,1)
      y_odin <- mod$run(t)
      out_odin <- as.data.frame(y_odin)
      out_odin = out_odin %>%
        mutate(
          `t`=`t`,
          `S[1]`=`US[1]`+`AES[1]`+`MES[1]`,
          `Pen_S[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`,
          `Pen_I[1]`=`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`,
          `Pen_R[1]`=`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          `Macro_S[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`,
          `Macro_R[1]`=`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
         
          `CmNsR[1]`=`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          `Totcarrier[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          `Tot[1]`=`US[1]`+`AES[1]`+`MES[1]`+`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          `Rcr`=`Rcr`,
          .keep = "none"
        )
      out_odin = out_odin %>%
        mutate(
          `t`=`t`,
          `Pen_S`=`Pen_S[1]`/`Totcarrier[1]`,
          `Pen_I`=`Pen_I[1]`/`Totcarrier[1]`,
          `Pen_R`=`Pen_R[1]`/`Totcarrier[1]`,
          `Macro_S`=`Macro_S[1]`/`Totcarrier[1]`,
          `Macro_R`=`Macro_R[1]`/`Totcarrier[1]`,
          `Multi_R`=`CmNsR[1]`/`Totcarrier[1]`,
          `Totcarrier_T`=`Totcarrier[1]`/`Tot[1]`,
          `Cross_T`= `CmNsR[1]`/(`Pen_I[1]`+`Pen_R[1]`),
          `Rcr`=`Rcr`,
          .keep = "none"
        )
      out_odin$Reduction<-j
      out_odin$Scenario<-k
      df<-rbind(df,out_odin)
      }
   }
  return(df)
  
}

```

```{r datframe delay, before and during shortages }

#Donnes 2021 otites pour penicillines: 
d2=0.075/0.53; d3=0.075/0.53; d4=0.085/0.53; d5=0.09/0.53; d6=0.12/0.53; d7=0.075/0.53; d8=0.01/0.53 
Rcr=0.58; Rmacro=0.28; Ramox=0.43; pi=0.52
ConsoAmox=0.95; ConsoMacro=0.083;Lambda=1/43
InvasionRate=4.8*10**(-7)


df<-LancementReduction(c(0.58,Ramox,Rmacro,ConsoAmox,ConsoMacro),100)
df_beforeshortage<- subset(df, Reduction %in% c("1"))
df<-LancementReduction(c(0.58,Ramox,Rmacro,ConsoAmox,ConsoMacro),365)
df_shortage<- subset(df, Reduction %in% c("3"))
df_shortage <- df_shortage %>%
  mutate(t = t + 100)
dfRcr058<-rbind(df_beforeshortage,df_shortage)

df<-LancementReduction(c(0.28,Ramox,Rmacro,ConsoAmox,ConsoMacro),100)
df_beforeshortage<- subset(df, Reduction %in% c("1"))
df<-LancementReduction(c(0.28,Ramox,Rmacro,ConsoAmox,ConsoMacro),365)
df_shortage<- subset(df, Reduction %in% c("3"))
df_shortage <- df_shortage %>%
  mutate(t = t + 100)
dfRcr028<-rbind(df_beforeshortage,df_shortage)
dfRcr<-rbind(dfRcr058,dfRcr028)

```

```{r ggplot evolution Figure 1 with Rcr=0.58 and 0.28}

out_long= dfRcr %>% pivot_longer(
  cols = `Pen_S`:`Totcarrier_T`,
  names_to = c("Antibiotique","Compartment"),
  names_pattern = "([A-Za-z0-9]+)_(.)",
  values_to = "count"
)

out_long <- subset(out_long, Antibiotique %in% c("Pen","Macro","Multi"))

out_long$Compartment <- factor(out_long$Compartment, levels = c("S", "I", "R"))
out_long$Antibiotique <- factor(out_long$Antibiotique, levels = c("Pen", "Macro", "Multi"))

labeller_fig1=labeller(Scenario=c("1"="S1","2"="S2","3"="S3","4"="S4"), Antibiotique=c("Pen"="Penicillin ","Macro"="Macrolide ","Multi"="Multidrug"))


p<-ggplot(out_long,aes(x=t,y=count,colour=Compartment,linetype = as.factor(Rcr)))+
  geom_rect(aes(xmin =100, xmax = Inf, ymin = -Inf, ymax = Inf),fill = "#FFE4E1", alpha = 0.04,inherit.aes = FALSE)+
  # geom_text(data = dplyr::filter(out_long,t==0),aes(label = round(count, 2)),vjust = -0.5, hjust = -0.3,show.legend = FALSE,size=7,face = "bold") +
  # geom_text(data = dplyr::filter(out_long,t==465),aes(label = round(count, 2)),vjust = -0.5, hjust = 0.7,show.legend = FALSE,size=7,face = "bold") +
  geom_line(linewidth=1.5)+
  scale_linetype_manual(name = "Rcr",values = c( "0.28" = "dashed", "0.58" = "solid"), labels = c("0.28", "0.58")) +
  scale_color_manual(values=c(R="#FF6347",S="#32CD32",I="#FFD700" ),name = "Antibiotic sensitivity level", labels = c("Susceptible", "Intermediate", "Resistant"))+
  xlab("Time (days)")+ylab("Proportion")+
  coord_cartesian(ylim = c(0, 0.85)) +
  facet_rep_grid(Scenario~Antibiotique,repeat.tick.labels = TRUE, labeller = labeller_fig1)+
  theme_clean()+
  theme(legend.background = element_rect(fill = "white", colour = "black"),legend.key.width =unit(3, "cm"),
        legend.title=element_text(size = 22),legend.text=element_text(size = 20),
        legend.direction = "vertical",legend.box = "horizontal", legend.box.just = "center",legend.position = "bottom",
        axis.text = element_text(size =18),axis.title = element_text(size = 20),
        strip.text = element_text(size = 25, face = "bold",hjust = 0.5),strip.placement = "outside",
        panel.border = element_blank() ,plot.background = element_blank())


pdf(filename = here::here("Figures", "Figure1Supplementary_VariationRcr.pdf"), width = 1200/81, height = 1200/81)
p
dev.off()

```



