---
title: "RunDifferentShortageLevels_Figure2"
output: html_document
date: "2024-07-10"
editor_options: 
  chunk_output_type: console
---

```{r library}

library(ggplot2)
library(tidyr)
library(dplyr)
library(reshape2)
library(ggpubr)
library(socialmixr)
library("RColorBrewer")
library(rmarkdown)
library(plotly)
library(demodelr)
library(forcats)
library(ggh4x)
library(lemon)
library(ggthemes)
library(khroma)
library(extrafont)
library(here)
library(lemon)
library(gridExtra)

```

##Figure 2

```{r plot figure 2 boxplot penurie proportion 0% à 100%}

dfnew <- read.csv(here::here("Files", "fichierCombine070225_0to100.csv"))

df<-dfnew
df$Value <- as.numeric(df$Value)
df <- df %>% filter(!is.na(Value))

df <- subset(df, Outcome %in% c("PropAns","PropMr","PropAnsMr","IncidenceInfectionsGraves"))

desired_order <- c("PropAns","PropMr","PropAnsMr","IncidenceInfectionsGraves", "IncidenceInfectionsGravesAns","IncidenceInfectionsGravesMr","IncidenceInfectionsGravesAnsMr")
df$Outcome <- factor(df$Outcome, levels = (desired_order))

# Calculer les valeurs baseline pour reduction = 0 pour chaque combinaison de scenario, outcome, et Lambda à t=365
baseline <- df %>%
  filter(Reduction == 1) %>%
  select(Scenario, Outcome, Lambda,pi, baseline_value = Value)

# # Joindre les valeurs baseline aux données originales
df <- df %>%
  left_join(baseline, by = c("Scenario", "Outcome", "Lambda","pi")) %>%
  mutate(Value =(Value - baseline_value)*100/baseline_value)

df_summary <- df %>%
  group_by(Scenario,Reduction, Outcome) %>%
  summarize(MedianValue = median(Value) )

df_summary

df<-df %>%left_join(df_summary, by = c("Scenario","Reduction", "Outcome"))

p<-ggplot(subset(df))+ #il faut utiliser la valeur Mean
  geom_line(aes(x=as.numeric(Reduction),y=MedianValue, color=as.factor(Scenario)),linetype = "longdash",linewidth=1)+
  geom_boxplot(aes(x=as.factor(Reduction),y=Value, fill=as.factor(Scenario)), position = position_dodge(),outlier.shape = NA)+
  scale_color_manual(name = "Strategies", labels = c("Consumption frequency reduction (S1)","Treatment duration reduction (S2)","Dose/day reduction (S3)","Alternative treatment (S4)"),values=c("red" ,"green", "blue","#FDC257"))+
  scale_fill_manual(name = "Strategies", labels = c("Consumption frequency reduction (S1)","Treatment duration reduction (S2)","Dose/day reduction (S3)","Alternative treatment (S4)"),values=c("red" ,"green", "blue","#FDC257"))+
    xlab("Different level of shortage (%)")+
  #ylab(expression(atop("Proportion", paste(""))))+
  ylab(expression(atop("Relative variation (%)", paste(""))))+
  facet_wrap(~Outcome,labeller = labeller(Outcome = c("PropAns" = "Penicillin-non-susceptible \nS. pneumoniae proportion","PropMr"="Macrolide-resistant \nS. pneumoniae proportion", "PropAnsMr"="Multidrug-resistant \nS. pneumoniae proportion","IncidenceInfectionsGraves" = "IPD incidence" )),scales = "free", ncol=2)+
  scale_x_discrete(labels = c("0","5","10","15","20", "25","30" ,"35","40","45","50","55","60","65","70","75","80","85","90","95","100"))+
theme_clean()+
  theme(axis.text = element_text(size = 16),axis.title = element_text(size = 18),
        legend.title=element_text(size = 16),legend.text=element_text(size = 14),
        legend.key.height = unit(0.8, "cm"),legend.key.width = unit(0.8, "cm"),
        strip.text = element_text(size = 18, face = "bold",hjust = 0.5),strip.placement = "outside",
        panel.border =element_blank(),plot.background = element_blank())

grid.arrange(p)

pdf(file = here::here("Figures", "Figure2Boxplot0to100.pdf"), width = 1400/81, height = 800/81)
grid.arrange(p)
dev.off()



```


```{r values of the changes observed in Figure 2 boxplot }

dfnew <- read.csv(here::here("Files", "fichierCombine070225_0to100.csv"))

df<-dfnew
df <- subset(df, Reduction %in% c("1","6","11","16")) #0%, 25%, #50% and 75% of shortage

df$Value <- as.numeric(df$Value)
df <- df %>% filter(!is.na(Value))

baseline <- df %>%
  filter(Reduction == 1) %>%
  select(Scenario, Outcome, Lambda,pi, baseline_value = Value)

# # Joindre les valeurs baseline aux données originales
df <- df %>%
  left_join(baseline, by = c("Scenario", "Outcome", "Lambda","pi")) %>%
  mutate(Variation =(Value - baseline_value)*100/baseline_value)

df_summary <- df %>%
  group_by(Scenario,Reduction, Outcome) %>%
  summarize(MinVariation = min(Variation),MaxVariation = max(Variation), MedianVariation = median(Variation), SdVariation= sd(Variation) )

df_summary

```


## Figure 3

```{r Figure 3 with uncertainty and points for Lambda}

##datframe pour barplot
dfnew <- read.csv(here::here("Files", "fichierCombine070225_0to100.csv"))
#Proportion
df<-dfnew
df<-subset(df, select = -X)
df <- subset(df, Reduction %in% c("1","11")) #0% and #50% of shortage
df <- subset(df, Outcome %in% c("PropAns","PropMr","PropAnsMr"))
desired_order <- c("PropAns","PropMr","PropAnsMr")
df$Outcome <- factor(df$Outcome, levels = (desired_order))
df$Value <- as.numeric(df$Value)

# Supprimer les lignes où 'value' est NA
dfP <- df %>% filter(!is.na(Value))

# Calculer les statistiques pour les lignes à 0% de réduction
summary_statsP <- dfP %>% 
  filter(Reduction == 1) %>%
  group_by(Outcome, Scenario) %>%
  summarize(
    median_value = median(Value),
    q1_value = quantile(Value, 0.25),
    q3_value = quantile(Value, 0.75)
  )
#Infections
df<-dfnew
#df<-subset(df, select = -X)
df <- subset(df, Reduction %in% c("1","11"))
df <- subset(df, Outcome %in% c("IncidenceInfectionsGraves","IncidenceInfectionsGravesAns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesAnsMr"))

desired_order <- c("IncidenceInfectionsGraves","IncidenceInfectionsGravesAns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesAnsMr")
df$Outcome <- factor(df$Outcome, levels = (desired_order))
df$Value <- as.numeric(df$Value)

# Supprimer les lignes où 'value' est NA
dfI <- df %>% filter(!is.na(Value))

# Calculer les statistiques pour les lignes à 0% de réduction
summary_statsI <- dfI %>% 
  filter(Reduction == 1) %>%
  group_by(Outcome, Scenario) %>%
  summarize(
    median_value = median(Value),
    q1_value = quantile(Value, 0.25),
    q3_value = quantile(Value, 0.75)
  )

##datframe pour points
dfnew <- read.csv(here::here("Files", "fichierCombine070225MaxMinMean.csv"))
## dataframe for proprotion-related outcomes
df<-dfnew
#df<-subset(df, select = -X)
df <- subset(df, pi==0.52)
#df <- subset(df, Lambda >= 0.02 & Lambda <= 0.025)
df <- subset(df, Reduction %in% c("1","3"))
df <- subset(df, Outcome %in% c("PropAns","PropMr","PropAnsMr"))
desired_order <- c("PropAns","PropMr","PropAnsMr")
df$Outcome <- factor(df$Outcome, levels = (desired_order))
df$Value <- as.numeric(df$Value)
dfP_point<-df

df<-dfnew
#df<-subset(df, select = -X)
df <- subset(df, pi==0.52)
#df <- subset(df, Lambda >= 0.02 & Lambda <= 0.025)
df <- subset(df, Reduction %in% c("1","3"))
df <- subset(df, Outcome %in% c("IncidenceInfectionsGraves","IncidenceInfectionsGravesAns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesAnsMr"))

desired_order <- c("IncidenceInfectionsGraves","IncidenceInfectionsGravesAns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesAnsMr")
df$Outcome <- factor(df$Outcome, levels = (desired_order))
df$Value <- as.numeric(df$Value)

dfI_point<-df


pP<-ggplot(dfP,aes(x=as.factor(Scenario),y=Value,fill=factor(Reduction)))+ #il faut utiliser la valeur Mean
  geom_hline(data = summary_statsP, aes(yintercept = median_value), color = "#008000", size = 1.5) +
  geom_hline(data = summary_statsP, aes(yintercept = q1_value), color = "#008000", linetype = "dashed") +
  geom_hline(data = summary_statsP, aes(yintercept = q3_value), color = "#008000", linetype = "dashed") +
  geom_boxplot(data = dfP %>% filter(Reduction == 11), position = position_dodge(),show.legend = FALSE)+
  geom_point(data = dfP_point %>% filter(Reduction == 3),aes(x=as.factor(Scenario),y=Value, colour = factor(Lambda)),size=5)+
  scale_colour_manual(values = c( "#FFD700",  "#FFA500", "#FF4500"),name=expression("Duration of colonization (" * lambda * ")"),labels = c("Min","Mean","Max"))+
  scale_fill_manual(name = "Réduction (%)", labels = c( "50"), values = c("11"="#FFD700"), guide = "none") +
  xlab("")+ylab(expression(atop("Proportion", paste(""))))+
  facet_wrap(~Outcome,labeller = labeller(Outcome = c("PropAns" = "Penicillin-non-susceptible\nS. pneumoniae","PropMr"="Macrolide-resistant\nS. pneumoniae", "PropAnsMr"="Multidrug-resistant\nS. pneumoniae")),scales = "free_y")+
  scale_x_discrete(labels = c("S1", "S2", "S3","S4"))+
   theme_clean()+
  theme(axis.text = element_text(size = 16),axis.title = element_text(size = 18),
        legend.title=element_text(size = 16),legend.text=element_text(size = 14),
        legend.key.height = unit(0.8, "cm"),legend.key.width = unit(0.8, "cm"),
        strip.text = element_text(size = 18, face = "bold",hjust = 0.5),strip.placement = "outside",
        panel.border =element_blank(),plot.background = element_blank())


pI<-ggplot(dfI,aes(x=as.factor(Scenario),y=Value,fill=factor(Reduction)))+
  geom_hline(data = summary_statsI, aes(yintercept = median_value), color = "#008000", size = 1.5) +
  geom_hline(data = summary_statsI, aes(yintercept = q1_value), color = "#008000", linetype = "dashed") +
  geom_hline(data = summary_statsI, aes(yintercept = q3_value), color = "#008000", linetype = "dashed") +
  geom_boxplot(data = dfI %>% filter(Reduction == 11), position = position_dodge(),show.legend = FALSE)+
  geom_point(data = dfI_point %>% filter(Reduction == 3),aes(x=as.factor(Scenario),y=Value, colour = factor(Lambda)),size=5)+
  scale_colour_manual(values = c( "#FFD700",  "#FFA500", "#FF4500"),name="Lambda",labels = c("Min","Mean","Max"))+
  scale_fill_manual(name = "Réduction (%)", labels = c("50"),values=c("11"="#FFD700"))+
  xlab("Strategies")+ylab(expression(atop("Annual incidence (per 100,000 children)", paste(""))))+
  #geom_text(aes(label=round(as.double(Value),2),colour=factor(Reduction)),position = position_dodge(0.9),vjust=-0.5,show.legend = FALSE)+
  facet_wrap(~Outcome,labeller =  labeller(Outcome = c("IncidenceInfectionsGraves" = "IPD","IncidenceInfectionsGravesAns"="IPD penicillin-non-\nsusceptible", "IncidenceInfectionsGravesMr"="IPD macrolide-\nresistant ","IncidenceInfectionsGravesAnsMr"="IPD multidrug- \nresistant")),scales = "free_y",ncol=4)+scale_x_discrete(labels = c("S1", "S2", "S3","S4"))+
  theme_clean()+
  theme(axis.text = element_text(size = 16),axis.title = element_text(size = 18),
        legend.title=element_text(size = 16),legend.text=element_text(size = 14),
        legend.key.height = unit(0.8, "cm"),legend.key.width = unit(0.8, "cm"),
        strip.text = element_text(size = 18, face = "bold",hjust = 0.5),strip.placement = "outside",
        panel.border =element_blank(),plot.background = element_blank(),legend.position = "none")


pdf(file = here::here("Figures", "Figure3Lambda.pdf"), width = 1400/81, height = 750/81)
grid.arrange(pP,pI,  layout_matrix = rbind(c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NA),c(2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2)))
dev.off()

```


```{r values of the changes observed in Figure 3 }

dfnew <- read.csv(here::here("Files", "fichierCombine070225_0to100.csv"))

df<-dfnew
df <- subset(df, Reduction %in% c("1","11")) #0%, and 50% of shortage

df$Value <- as.numeric(df$Value)
df <- df %>% filter(!is.na(Value))

baseline <- df %>%
  filter(Reduction == 1) %>%
  select(Scenario, Outcome, Lambda,pi, baseline_value = Value)

# # Joindre les valeurs baseline aux données originales
# df <- df %>%
#   left_join(baseline, by = c("Scenario", "Outcome", "Lambda","pi")) %>%
#   mutate(Variation =(Value - baseline_value)*100/baseline_value)

df <- df %>%
  left_join(baseline, by = c("Scenario", "Outcome", "Lambda","pi")) %>%
  mutate(Variation =(Value))

df_summary <- df %>%
  group_by(Scenario,Reduction, Outcome) %>%
  summarize(MinValue = min(Variation),MaxValue = max(Variation), MedianValue = median(Variation) )

df_summary

```



## Supplementary figure 2 with parameter carriage of prevalenve (pi) varying

```{r  Supplementary figure 2 with uncertainty and points for pi}

##datframe pour barplot
dfnew <- read.csv(here::here("Files", "fichierCombine070225_0to100.csv"))
#Proportion
df<-dfnew
df<-subset(df, select = -X)
df <- subset(df, Reduction %in% c("1","11")) #0% and #50% of shortage
df <- subset(df, Outcome %in% c("PropAns","PropMr","PropAnsMr"))
desired_order <- c("PropAns","PropMr","PropAnsMr")
df$Outcome <- factor(df$Outcome, levels = (desired_order))
df$Value <- as.numeric(df$Value)

# Supprimer les lignes où 'value' est NA
dfP <- df %>% filter(!is.na(Value))

# Calculer les statistiques pour les lignes à 0% de réduction
summary_statsP <- dfP %>% 
  filter(Reduction == 1) %>%
  group_by(Outcome, Scenario) %>%
  summarize(
    median_value = median(Value),
    q1_value = quantile(Value, 0.25),
    q3_value = quantile(Value, 0.75)
  )
#Infections
df<-dfnew
#df<-subset(df, select = -X)
df <- subset(df, Reduction %in% c("1","11"))
df <- subset(df, Outcome %in% c("IncidenceInfectionsGraves","IncidenceInfectionsGravesAns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesAnsMr"))

desired_order <- c("IncidenceInfectionsGraves","IncidenceInfectionsGravesAns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesAnsMr")
df$Outcome <- factor(df$Outcome, levels = (desired_order))
df$Value <- as.numeric(df$Value)

# Supprimer les lignes où 'value' est NA
dfI <- df %>% filter(!is.na(Value))

# Calculer les statistiques pour les lignes à 0% de réduction
summary_statsI <- dfI %>% 
  filter(Reduction == 1) %>%
  group_by(Outcome, Scenario) %>%
  summarize(
    median_value = median(Value),
    q1_value = quantile(Value, 0.25),
    q3_value = quantile(Value, 0.75)
  )

##datframe pour points
dfnew <- read.csv(here::here("Files", "fichierCombine070225MaxMinMean.csv"))
## dataframe for proprotion-related outcomes
df<-dfnew
#df<-subset(df, select = -X)
#df <- subset(df, pi==0.52)
df <- subset(df, Lambda >= 0.02 & Lambda <= 0.025)
df <- subset(df, Reduction %in% c("1","3"))
df <- subset(df, Outcome %in% c("PropAns","PropMr","PropAnsMr"))
desired_order <- c("PropAns","PropMr","PropAnsMr")
df$Outcome <- factor(df$Outcome, levels = (desired_order))
df$Value <- as.numeric(df$Value)
dfP_point<-df

df<-dfnew
#df<-subset(df, select = -X)
#df <- subset(df, pi==0.52)
df <- subset(df, Lambda >= 0.02 & Lambda <= 0.025)
df <- subset(df, Reduction %in% c("1","3"))
df <- subset(df, Outcome %in% c("IncidenceInfectionsGraves","IncidenceInfectionsGravesAns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesAnsMr"))

desired_order <- c("IncidenceInfectionsGraves","IncidenceInfectionsGravesAns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesAnsMr")
df$Outcome <- factor(df$Outcome, levels = (desired_order))
df$Value <- as.numeric(df$Value)

dfI_point<-df


pP<-ggplot(dfP,aes(x=as.factor(Scenario),y=Value,fill=factor(Reduction)))+ #il faut utiliser la valeur Mean
  geom_hline(data = summary_statsP, aes(yintercept = median_value), color = "#008000", size = 1.5) +
  geom_hline(data = summary_statsP, aes(yintercept = q1_value), color = "#008000", linetype = "dashed") +
  geom_hline(data = summary_statsP, aes(yintercept = q3_value), color = "#008000", linetype = "dashed") +
  geom_boxplot(data = dfP %>% filter(Reduction == 11), position = position_dodge(),show.legend = FALSE)+
  geom_point(data = dfP_point %>% filter(Reduction == 3),aes(x=as.factor(Scenario),y=Value, colour = factor(pi)),size=5)+
  scale_colour_manual(values = c( "#FFD700",  "#FFA500", "#FF4500"),name="pi",labels = c("Min","Mean","Max"))+
  scale_fill_manual(name = "Réduction (%)", labels = c( "50"), values = c("11"="#FFD700"), guide = "none") +
  xlab("")+ylab(expression(atop("Proportion", paste(""))))+
  facet_wrap(~Outcome,labeller = labeller(Outcome = c("PropAns" = "Penicillin-non-susceptible\nS. pneumoniae","PropMr"="Macrolide-resistant\nS. pneumoniae", "PropAnsMr"="Multidrug-resistant\nS. pneumoniae")),scales = "free_y")+
  scale_x_discrete(labels = c("S1", "S2", "S3","S4"))+
   theme_clean()+
  theme(axis.text = element_text(size = 16),axis.title = element_text(size = 18),
        legend.title=element_text(size = 16),legend.text=element_text(size = 14),
        legend.key.height = unit(0.8, "cm"),legend.key.width = unit(0.8, "cm"),
        strip.text = element_text(size = 18, face = "bold",hjust = 0.5),strip.placement = "outside",
        panel.border =element_blank(),plot.background = element_blank())


pI<-ggplot(dfI,aes(x=as.factor(Scenario),y=Value,fill=factor(Reduction)))+
  geom_hline(data = summary_statsI, aes(yintercept = median_value), color = "#008000", size = 1.5) +
  geom_hline(data = summary_statsI, aes(yintercept = q1_value), color = "#008000", linetype = "dashed") +
  geom_hline(data = summary_statsI, aes(yintercept = q3_value), color = "#008000", linetype = "dashed") +
  geom_boxplot(data = dfI %>% filter(Reduction == 11), position = position_dodge(),show.legend = FALSE)+
  geom_point(data = dfI_point %>% filter(Reduction == 3),aes(x=as.factor(Scenario),y=Value, colour = factor(pi)),size=5)+
  scale_colour_manual(values = c( "#FFD700",  "#FFA500", "#FF4500"),name="pi",labels = c("Min","Mean","Max"))+
  scale_fill_manual(name = "Réduction (%)", labels = c("50"),values=c("11"="#FFD700"))+
  xlab("Strategies")+ylab(expression(atop("Annual incidence (per 100,000 children)", paste(""))))+
  #geom_text(aes(label=round(as.double(Value),2),colour=factor(Reduction)),position = position_dodge(0.9),vjust=-0.5,show.legend = FALSE)+
  facet_wrap(~Outcome,labeller =  labeller(Outcome = c("IncidenceInfectionsGraves" = "IPD","IncidenceInfectionsGravesAns"="IPD penicillin-non-\nsusceptible", "IncidenceInfectionsGravesMr"="IPD macrolide-\nresistant ","IncidenceInfectionsGravesAnsMr"="IPD multidrug- \nresistant")),scales = "free_y",ncol=4)+scale_x_discrete(labels = c("S1", "S2", "S3","S4"))+
  theme_clean()+
  theme(axis.text = element_text(size = 16),axis.title = element_text(size = 18),
        legend.title=element_text(size = 16),legend.text=element_text(size = 14),
        legend.key.height = unit(0.8, "cm"),legend.key.width = unit(0.8, "cm"),
        strip.text = element_text(size = 18, face = "bold",hjust = 0.5),strip.placement = "outside",
        panel.border =element_blank(),plot.background = element_blank(),legend.position = "none")

pdf(file = here::here("Figures", "FigureS2pi.pdf"), width = 1400/81, height = 750/81)
grid.arrange(pP,pI,  layout_matrix = rbind(c(1,1,1,1,1,1,1,1,1,1,1,1,1,NA,NA,NA,NA),c(2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2)))
dev.off()

```



