---
title: "BestScenariobyCountry_Figure6"
output: html_document
date: "2024-07-10"
editor_options: 
  chunk_output_type: console
---

```{r library}
library(ggplot2)
library(readxl)
library(tidyr)
library(dplyr)
library(reshape2)
library(ggpubr)
library(socialmixr)
data(polymod)
library("RColorBrewer")
library(rmarkdown)
library(plotly)
library(demodelr)
library(forcats)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(patchwork)
library(cowplot)
library(gridExtra)
library(ggflags)

```


```{r setup}

gen <- odin::odin("Script\\DeuxAgeHuitResistanceDeuxAntibiosOdin.R")

#Otites 2021 penicillines
d2=0.075/0.53; d3=0.075/0.53; d4=0.085/0.53; d5=0.09/0.53; d6=0.12/0.53; d7=0.075/0.53; d8=0.01/0.53
Lambda=1/43
pi=0.52
InvasionRate=4.8*10**(-7)

```


```{r optim sur le tau de portage}

OptimVi <- function(x,param) {
  Rcr=as.numeric(param[1])*(0.58/0.63)
  Ramox=as.numeric(param[2])*(0.43/0.32)
  Rmacro=as.numeric(param[3])*(0.28/0.23) 
  ConsoAmox=as.numeric(param[4])*(0.95/0.365)
  ConsoMacro=as.numeric(param[5])*(0.083/0.102)
  pi=as.numeric(param[6])
  Lambda=as.numeric(param[7])
  TreatmentDuration_Amox=as.numeric(param[8])
  TreatmentDuration_Macro=as.numeric(param[9])
  mod <- gen$new( US_0=c((70000000*(1-(0.0163+0.0016)))*(1-pi)*0.055),
                  UCm1_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  UCm1_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*(Rmacro-Rcr*Ramox)*0.055),
                  UCm2_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d2*0.055),
                  UCm2_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d2*0.055),
                  UCm3_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d3*0.055),
                  UCm3_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d3*0.055),
                  UCm4_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d4*0.055),
                  UCm4_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d4*0.055),
                  UCm5_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d5*0.055),
                  UCm5_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d5*0.055),
                  UCm6_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d6*0.055),
                  UCm6_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d6*0.055),
                  UCm7_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d7*0.055),
                  UCm7_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d7*0.055),
                  UCm8_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d8*0.055),
                  UCm8_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d8*0.055),
                  
                  AES_0=c((70000000*0.0163)*(1-pi)*0.055),
                  AECm1_S_0=c((70000000*0.0163)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  AECm1_R_0=c((70000000*0.0163)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  AECm2_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d2*0.055),
                  AECm2_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d2*0.055),
                  AECm3_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d3*0.055),
                  AECm3_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d3*0.055),
                  AECm4_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d4*0.055),
                  AECm4_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d4*0.055),
                  AECm5_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d5*0.055),
                  AECm5_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d5*0.055),
                  AECm6_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d6*0.055),
                  AECm6_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d6*0.055),
                  AECm7_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d7*0.055),
                  AECm7_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d7*0.055),
                  AECm8_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d8*0.055),
                  AECm8_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d8*0.055),
                  
                  MES_0=c((70000000*0.0016)*(1-pi)*0.055),
                  MECm1_S_0=c((70000000*0.0016)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  MECm1_R_0=c((70000000*0.0016)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  MECm2_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d2*0.055),
                  MECm2_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d2*0.055),
                  MECm3_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d3*0.055),
                  MECm3_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d3*0.055),
                  MECm4_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d4*0.055),
                  MECm4_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d4*0.055),
                  MECm5_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d5*0.055),
                  MECm5_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d5*0.055),
                  MECm6_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d6*0.055),
                  MECm6_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d6*0.055),
                  MECm7_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d7*0.055),
                  MECm7_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d7*0.055),
                  MECm8_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d8*0.055),
                  MECm8_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d8*0.055),
                  
                  # Fitness cost
                  fA1=1, fA2=0.9999748 , fA3=0.9916096 , fA4=0.9420954 , fA5=0.9192299 , fA6=0.9192278 , fA7=0.9192375 , fA8=0.9194097 ,
                  fMS=1,fMR=0.9938509 ,
                  a1=0,a2=0,a3=0,a4=1,a5=1,a6=1,a7=1,a8=1,
                  V=c(x[1]),
                  
                  Beta=matrix(c(1),nrow = 1, ncol = 1,byrow = TRUE),
                  
                  #Consommation normale observée
                  Phi_A=c(ConsoAmox/365),
                  Phi_M=c(ConsoMacro/365),
                  
                  Mu=c(0),  #c((0.76*10**(-3))/365,(0.1*10**(-3))/365,(2.16*10**(-3))/365,(50*10**(-3))/365),
                  mu0=0,
                  Lambda=c(Lambda),
                  gamma_A=1/TreatmentDuration_Amox,
                  gamma_M=1/TreatmentDuration_Macro,
                  
                  #Dose calculées sur les articles
                  dose1_A= 1, #500mg,q12h MIC=0.06
                  dose2_A=0.93,#500mg,q12h MIC=0.125
                  dose3_A=0.47,#500mg,q12h MIC=0.25
                  dose4_A=0.06,#500mg,q12h MIC=0.5
                  dose5_A=0,#500mg,q12h MIC=1
                  dose6_A=0,#500mg,q12h MIC=2
                  dose7_A=0, #500mg,q12h MIC=4
                  dose8_A=0, #500mg,q8h MIC=8
                  dose1_M= 1.006924, #500mg,q12h MIC=0.06
                  dose2_M=0.03449561,#500mg,q12h MIC=0.125
                  
                  theta=0.5,
                  N_age=1)
  
  t <- seq(0, 365*1,0.1)
  y_odin <- mod$run(t)
  out_odin <- as.data.frame(y_odin)
  
  out_odin=out_odin[c(nrow(out_odin)),]
  
  out_odin = out_odin %>%
    mutate(
      `t`=`t`,
      `Totcarrier[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
      
      `Tot[1]`=`US[1]`+`AES[1]`+`MES[1]`+`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
      
      .keep = "none"
    )
  out_odin = out_odin %>%
    mutate(
      `t`=`t`,
      `Totcarrier[1]`=`Totcarrier[1]`/`Tot[1]`,
      .keep = "none"
    )
  
  f=out_odin
  
  p1=as.numeric(f[2])
  
  #cat(x[1],"",x[2], "",x[3], "",x[4])
  
  return(abs(pi-p1)**2)
}


```



```{r simulation penurie}

RunShortageCountry <- function(param,country){
  df<-data.frame(Scenario=numeric(), Reduction=numeric(),Country=character(), Outcome=character(), Value=numeric() )
    Rcr=as.numeric(param[1])*(0.58/0.63)
    Ramox=as.numeric(param[2])*(0.43/0.32)
    Rmacro=as.numeric(param[3])*(0.28/0.23) 
    ConsoAmox=as.numeric(param[4])*(0.95/0.365)
    ConsoMacro=as.numeric(param[5])*(0.083/0.102)
    pi=as.numeric(param[6])
    Lambda=as.numeric(param[7])
    TreatmentDuration_Amox=as.numeric(param[8])
    TreatmentDuration_Macro=as.numeric(param[9])
    
    Vopti=as.numeric((Optim_vi=optim(c(0.01),OptimVi,param=param,control = list(maxit = 20000)))$par)
    print(Vopti)
  
   for (k in 1:4){
     print(k)
    if(k==1){ ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.06,0,0,0,0,0,
          1,0.47,0,0,0,0,0,0,
          1,0.06,0,0,0,0,0,0),ncol=4)
    ReductionDuree=c(1,1,1,1)
    ReductionFreq=c(1,1,1,1)
    AugmentationFreq=c(0,0,0,0)
    }
     
    if(k==2){ ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(1,0.75,0.5,0.25)
    ReductionFreq=c(1,1,1,1)
    AugmentationFreq=c(0,0,0,0)
    }
    
    if(k==3){ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(1,1,1,1)
    ReductionFreq=c(1,0.75,0.5,0.25)
    AugmentationFreq=c(0,0,0,0)
    }
    
    if(k==4){ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(1,1,1,1)
    ReductionFreq=c(1,0.75,0.5,0.25)
    AugmentationFreq=c(0,0.25,0.5,0.75)}
    for(j in 1:4){
      print(j)
      mod <- gen$new( US_0=c((70000000*(1-(0.0163+0.0016)))*(1-pi)*0.055),
                  UCm1_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  UCm1_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*(Rmacro-Rcr*Ramox)*0.055),
                  UCm2_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d2*0.055),
                  UCm2_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d2*0.055),
                  UCm3_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d3*0.055),
                  UCm3_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d3*0.055),
                  UCm4_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d4*0.055),
                  UCm4_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d4*0.055),
                  UCm5_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d5*0.055),
                  UCm5_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d5*0.055),
                  UCm6_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d6*0.055),
                  UCm6_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d6*0.055),
                  UCm7_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d7*0.055),
                  UCm7_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d7*0.055),
                  UCm8_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d8*0.055),
                  UCm8_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d8*0.055),
                  
                  AES_0=c((70000000*0.0163)*(1-pi)*0.055),
                  AECm1_S_0=c((70000000*0.0163)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  AECm1_R_0=c((70000000*0.0163)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  AECm2_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d2*0.055),
                  AECm2_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d2*0.055),
                  AECm3_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d3*0.055),
                  AECm3_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d3*0.055),
                  AECm4_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d4*0.055),
                  AECm4_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d4*0.055),
                  AECm5_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d5*0.055),
                  AECm5_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d5*0.055),
                  AECm6_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d6*0.055),
                  AECm6_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d6*0.055),
                  AECm7_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d7*0.055),
                  AECm7_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d7*0.055),
                  AECm8_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d8*0.055),
                  AECm8_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d8*0.055),
                  
                  MES_0=c((70000000*0.0016)*(1-pi)*0.055),
                  MECm1_S_0=c((70000000*0.0016)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  MECm1_R_0=c((70000000*0.0016)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  MECm2_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d2*0.055),
                  MECm2_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d2*0.055),
                  MECm3_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d3*0.055),
                  MECm3_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d3*0.055),
                  MECm4_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d4*0.055),
                  MECm4_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d4*0.055),
                  MECm5_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d5*0.055),
                  MECm5_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d5*0.055),
                  MECm6_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d6*0.055),
                  MECm6_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d6*0.055),
                  MECm7_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d7*0.055),
                  MECm7_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d7*0.055),
                  MECm8_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d8*0.055),
                  MECm8_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d8*0.055),
                      
                  fA1=1, fA2=0.9999748 , fA3=0.9916096 , fA4=0.9420954 , fA5=0.9192299 , fA6=0.9192278 , fA7=0.9192375 , fA8=0.9194097 ,
                  fMS=1,fMR=0.9938509 ,
                  a1=0,a2=0,a3=0,a4=1,a5=1,a6=1,a7=1,a8=1,
                  V=c(Vopti),
               
                  Beta=matrix(c(1),nrow = 1, ncol = 1,byrow = TRUE),
               
                  
                      #Consommation normale observée adultes 
                      Phi_A=c(ConsoAmox*ReductionFreq[j]/(365)),
                      Phi_M=c((ConsoMacro*(1+((ConsoAmox)/(ConsoMacro))*AugmentationFreq[j]))/365),
                      
                      Mu=c(0),  #c((0.76*10**(-3))/365,(0.1*10**(-3))/365,(2.16*10**(-3))/365,(50*10**(-3))/365),
                      mu0=0,
                      Lambda=c(Lambda),
                      gamma_A=1/(TreatmentDuration_Amox*ReductionDuree[j]),
                      gamma_M=1/TreatmentDuration_Macro,
                      
                      #Dose 500mg, q8h
                      dose1_A=ReductionDose[1,j],
                      dose2_A=ReductionDose[2,j],
                      dose3_A=ReductionDose[3,j],
                      dose4_A=ReductionDose[4,j],
                      dose5_A=ReductionDose[5,j],
                      dose6_A=ReductionDose[6,j],
                      dose7_A=ReductionDose[7,j],
                      dose8_A=ReductionDose[8,j],
                      dose1_M= 1.006924, #500mg,q12h MIC=0.06
                      dose2_M=0.03449561,#500mg,q12h MIC=0.125
                      
                      theta=0.5,
                      N_age=1)
      
      t <- seq(0, 365*1,1)
      y_odin <- mod$run(t)
      out_odin <- as.data.frame(y_odin)
      out_odin = out_odin %>%
        mutate(
          `t`=`t`,
          `S[1]`=`US[1]`+`AES[1]`+`MES[1]`,
          `Cm1[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`,
          `Cm2[1]`=`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`,
          `Cm3[1]`=`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`,
          `Cm4[1]`=`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`,
          `Cm5[1]`=`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`,
          `Cm6[1]`=`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`,
          `Cm7[1]`=`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`,
          `Cm8[1]`=`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          `CmS[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`,
          `CmR[1]`=`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          `CmNsR[1]`=`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          `Totcarrier[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          `Tot[1]`=`US[1]`+`AES[1]`+`MES[1]`+`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          .keep = "none"
        )
      out_odin = out_odin %>%
      mutate(
        `InfectionsGraves[1]`=InvasionRate*`Totcarrier[1]`,
        `InfectionsGravesPSSP[1]`=InvasionRate*`Cm1[1]`,
        `InfectionsGravesPNSP[1]`=InvasionRate*(`Cm2[1]`+`Cm3[1]`+`Cm4[1]`+`Cm5[1]`+`Cm6[1]`+`Cm7[1]`+`Cm8[1]`),
        `InfectionsGravesMR[1]`=InvasionRate*`CmR[1]`,
        `InfectionsGravesPNSPMR[1]`=InvasionRate*`CmNsR[1]`,
        )
    
    out_odin = out_odin %>%
      mutate(
        `InfectionsGravesCumulees[1]`=cumsum(`InfectionsGraves[1]`),
        `InfectionsGravesPSSPCumulees[1]`=cumsum(`InfectionsGravesPSSP[1]`),
        `InfectionsGravesPNSPCumulees[1]`=cumsum(`InfectionsGravesPNSP[1]`),
        `InfectionsGravesMRCumulees[1]`=cumsum(`InfectionsGravesMR[1]`),
        `InfectionsGravesPNSPMRCumulees[1]`=cumsum(`InfectionsGravesPNSPMR[1]`),
        )
    
    out_odin=out_odin[c(nrow(out_odin)),]
    
    As1<-(out_odin$`Cm1[1]`)/(out_odin$`Totcarrier[1]`) 
    
    Ans1=1-As1
    
    Ms1<-(out_odin$`CmS[1]`)/(out_odin$`Totcarrier[1]`)
    
    Mr1<-(out_odin$`CmR[1]`)/(out_odin$`Totcarrier[1]`)
    
    AnsMr1<-(out_odin$`CmNsR[1]`)/(out_odin$`Totcarrier[1]`)
    
    I1<-out_odin$`InfectionsGravesCumulees[1]` #*100000/(70000000*0.055)
    
    Is1<-out_odin$`InfectionsGravesPSSPCumulees[1]` #*100000/(70000000*0.055)
    
    IAns1<-out_odin$`InfectionsGravesPNSPCumulees[1]` #*100000/(70000000*0.055)
    
    IMr1<-out_odin$`InfectionsGravesMRCumulees[1]` #*100000/(70000000*0.055)
    
    IAnsMr1<-out_odin$`InfectionsGravesPNSPMRCumulees[1]` #*100000/(70000000*0.055)
      
      outputAns=Ans1
      outputMr=Mr1
      outputAnsMr=AnsMr1
      
      outputIgrave=I1
      outputIgraveS=Is1
      outputIgraveAns=IAns1
      outputIgraveMr=IMr1
      outputIgraveAnsMr=IAnsMr1
      
      df2<-data.frame(Scenario=numeric(), Reduction=numeric(),Country=character(), Outcome=character(), Value=numeric() )
      df2[1,]<-c(k,j,country,"PropPns",outputAns)
      df2[2,]<-c(k,j,country,"PropMr",outputMr)
      df2[3,]<-c(k,j,country,"PropPnsMr",outputAnsMr)
      df2[4,]<-c(k,j,country,"IncidenceInfectionsGraves",outputIgrave)
      df2[5,]<-c(k,j,country,"IncidenceInfectionsGravesS",outputIgraveS)
      df2[6,]<-c(k,j,country,"IncidenceInfectionsGravesPns",outputIgraveAns)
      df2[7,]<-c(k,j,country,"IncidenceInfectionsGravesMr",outputIgraveMr)
      df2[8,]<-c(k,j,country,"IncidenceInfectionsGravesPnsMr",outputIgraveAnsMr)
      df=rbind(df,df2)
      }
   }
  return(df)
  
    }


```



```{r Lancement penurie sur tous les Pays}

#Dataframe with adult datas
df<-read_excel("Files\\DataframeParametresPays.xlsx")

dfnew<-data.frame(Scenario=numeric(), Reduction=numeric(),Country=character(), Outcome=character(), Value=numeric() )

for(i in 1:nrow(df)){
  print(df$Pays[i])
  param=c(df$Rcr[i],df$Ramox[i],df$Rmacro[i],df$PhiAmox[i],df$PhiMacro[i],0.52,1/43,7,7)
  df_pays<-RunShortageCountry(param,df$Pays[i])
  dfnew=rbind(dfnew,df_pays)
}



```


```{r plot consommation Resistance tous les Pays}

#Dataframe with adult datas
df<-read_excel("C:\\Users\\Aurélie\\Documents\\AntibioticShortage\\DataframeParametresPays.xlsx")

df$country <- tolower(c("AT", "BE", "HR", "CZ", "DK", "EE","FI", "FR", "DE", "HU", "IE",
                     "IT", "LT", "NL", "NO", "PL", "PT", "SI", "ES", "SE"))

# Ouvrir un périphérique graphique pour sauvegarder le plot en tant qu'image PNG
#
png("C:\\Users\\Aurélie\\Documents\\AntibioticShortage\\Figures\\FigureCountriesConsoResistance.png", width = 1200, height = 500)

p<-ggplot(df, aes(x = PhiAmox, y = Ramox)) +
  geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "dashed") +
  geom_flag(aes(country=country),size=10) +
  geom_text(aes(label = Pays), hjust = 0.7, vjust = 1.5, size = 5,show.legend=FALSE) +
  labs(x = expression(Phi^Amox ~ '(/hab/year)'), y = "PNSP")+
  theme_clean()+
  theme(legend.background = element_rect(fill = "white", colour = "black"),legend.key.size = unit(0.8, "cm"),
        legend.title=element_text(size = 16),legend.text=element_text(size = 26),
        legend.direction = "vertical",legend.box = "horizontal", legend.box.just = "center",legend.position = c(0.8,0.8),
        axis.text = element_text(size =20),axis.title = element_text(size = 26),
        panel.border = element_blank() ,plot.background = element_blank())

# Regression lineaire
# fit <- lm(PhiAmox ~ Ramox, data = df)
# summary(fit)

# Ajouter l'équation et le R^2 au graphique
# eq <- paste0("R² = ", round(summary(fit)$r.squared, 4))
# 
# p<-p+annotate("text", x = 0.32, y = 0.23, label = eq, size = 5, color = "black", parse = FALSE)
# p

p2<-ggplot(df, aes(x = PhiMacro, y = Rmacro)) +
  geom_flag(aes(country=country),size=10) +
  geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "dashed") +
  geom_text(aes(label = Pays), hjust = 0.7, vjust = 1.5, size = 5,show.legend=FALSE) +
  labs(x = expression(Phi^Macro~ '(/hab/year)'), y = "MR") +
  theme_clean()+
  theme(legend.background = element_rect(fill = "white", colour = "black"),legend.key.size = unit(0.8, "cm"),
        legend.title=element_text(size = 16),legend.text=element_text(size = 26),
        legend.direction = "vertical",legend.box = "horizontal", legend.box.just = "center",legend.position = c(0.8,0.8),
        axis.text = element_text(size =20),axis.title = element_text(size = 26),
        panel.border = element_blank() ,plot.background = element_blank())

# Regression lineaire
# fit2 <- lm(PhiMacro ~ Rmacro, data = df)
# 
# # Ajouter l'équation et le R^2 au graphique
# eq2 <- paste0("R² = ", round(summary(fit2)$r.squared, 4))
# 
# p2<-p2+annotate("text", x = 0.18, y = 0.28, label = eq2, size = 5, color = "black", parse = FALSE)


grid.arrange(p,p2,ncol=2)

# Fermer le périphérique graphique
dev.off()



```


```{r plot variation des outcomes en % penurie pour tous les Pays }

df<-dfnew
df$Value <- as.numeric(df$Value)
df<-as.data.frame(df)
df <- subset(df, Reduction %in% c("1","3"))


df <- subset(df, Outcome %in%c("PropPns","PropMr","PropPnsMr"))

new_df <- df %>%
  group_by(Scenario,Country, Outcome) %>%
  summarise(Variation = ((Value[Reduction == 3] - Value[Reduction == 1])*100/(Value[Reduction == 1])))

df=as.data.frame(new_df)

min_values <- df %>%
  group_by(Country, Outcome) %>%
  summarize(MinValue = min(Variation))

df <- merge(df, min_values, by = c("Country", "Outcome"))

desired_order <- c("PropPns","PropMr","PropPnsMr")

# desired_order <- c("PropPns","PropMr","PropPnsMr",
#                    "IncidenceInfectionsGraves","IncidenceInfectionsGravesPns",
#                    "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesPnsMr")

df$Outcome <- factor(df$Outcome, levels = rev(desired_order))


png("C:\\Users\\maurinau\\Documents\\AntibioticShortage\\Figures\\Figure6_HeatMapPaysRelativeVariationProportion.png", width = 1600, height = 1000)

ggplot(df, aes(x = as.factor(Scenario), y = Outcome, fill = Variation)) +
  geom_tile() +
  geom_text(aes(label = sprintf("%.2f", round(Variation,digits=2))),show.legend = TRUE, size=5) +
  scale_color_manual(name=" Value",labels=c("lowest value",""), guide=guide_legend()) +
  geom_tile(data = df %>% filter(Variation == MinValue), aes(x = as.factor(Scenario), y = Outcome), color = "black", size = 1.5, fill = NA) +
  scale_fill_gradient2(low = "#075AFF",mid="white", high = "#FF6347") +  # Choix des couleurs
  labs(x = "Scenarios", y = "Outcome") +
  facet_wrap(~Country)+
  scale_x_discrete(labels = c("S1", "S2", "S3","S4"))+
  scale_y_discrete(labels = c("PropPns" = "Proportion of penicillin non-susceptible strains","PropMr"="Proprotion of macrolide resistant strains", "PropPnsMr"="Proportion multi-resistant strains"))+labs(x = NULL, y = NULL)+
  theme_bw()+
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 16),legend.title=element_text(size = 14),
        legend.text=element_text(size = 16),
        legend.key.height = unit(0.8, "cm"),legend.key.width = unit(0.8, "cm"),
        #legend.box.background = element_rect(colour = "black", fill = NA, size = 1),
        strip.text = element_text(size = 16,face = "bold"),strip.background = element_rect(fill = "white"), 
        panel.border =element_rect(colour = "black", fill = NA, size = 1.5))

 # Fermer le périphérique graphique
dev.off()


```



```{r plot variation du nombre de cas pour tous les Pays }
#Retirer le 1000000/(70000000*0.055) dans le runshortage

df<-dfnew
df$Value <- as.numeric(df$Value)
df<-as.data.frame(df)
df <- subset(df, Reduction %in% c("1","3"))

df <- subset(df, Outcome %in%c("IncidenceInfectionsGraves","IncidenceInfectionsGravesS","IncidenceInfectionsGravesPns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesPnsMr"))

new_df <- df %>%
  group_by(Scenario,Country, Outcome) %>%
  #summarise(Variation = ((Value[Reduction == 3] - Value[Reduction == 1])*100/(Value[Reduction == 1])))
  summarise(Variation = ((Value[Reduction == 3] - Value[Reduction == 1])))
df=as.data.frame(new_df)

min_values <- df %>%
  group_by(Country, Outcome) %>%
  summarize(MinValue = min(Variation))

df <- merge(df, min_values, by = c("Country", "Outcome"))

desired_order <- c("IncidenceInfectionsGraves","IncidenceInfectionsGravesS","IncidenceInfectionsGravesPns",
                   "IncidenceInfectionsGravesMr","IncidenceInfectionsGravesPnsMr")

df$Outcome <- factor(df$Outcome, levels = rev(desired_order))


png("C:\\Users\\Aurélie\\Documents\\AntibioticShortage\\Figures\\Figure6_HeatMapPaysAbsoluteVariationIncidence.png", width = 1600, height = 1000)

ggplot(df, aes(x = as.factor(Scenario), y = Outcome, fill = Variation)) +
  geom_tile() +
  geom_text(aes(label = sprintf("%.2f", round(Variation,digits=2))),show.legend = TRUE, size=5) +
  scale_color_manual(name=" Value",labels=c("lowest value",""), guide=guide_legend()) +
  geom_tile(data = df %>% filter(Variation == MinValue), aes(x = as.factor(Scenario), y = Outcome), color = "black", size = 1.5, fill = NA) +
  scale_fill_gradient2(low = "#075AFF",mid="white", high = "#FF6347") +  # Choix des couleurs
  labs(x = "Scenarios", y = "Outcome", title = "Absolute variation in outcomes over 1 year, for a shortage of 50% for different countries") +
  facet_wrap(~Country)+
  scale_x_discrete(labels = c("S1", "S2", "S3","S4"))+
  scale_y_discrete(labels = c("IncidenceInfectionsGraves" = "Number of severe infections","IncidenceInfectionsGravesS"="Number of severe penicillin-susceptible infections","IncidenceInfectionsGravesPns"="Number of severe penicillin non-susceptible infections", "IncidenceInfectionsGravesMr"="Number of severe macrolide resistant infections","IncidenceInfectionsGravesPnsMr"="Number of severe multi-resistant infections"))+labs(x = NULL, y = NULL)+
  theme_bw()+
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 16),legend.title=element_text(size = 14),
        legend.text=element_text(size = 16),
        legend.key.height = unit(0.8, "cm"),legend.key.width = unit(0.8, "cm"),
        strip.text = element_text(size = 16,face="bold"),strip.background = element_rect(fill = "white"),
        panel.border =element_rect(colour = "black", fill = NA, size = 1.5))

 # Fermer le périphérique graphique
dev.off()


```



```{r carte}

# Obtenir les données des pays
europe <- ne_countries(scale = "medium", continent = "Europe", returnclass = "sf")


df<-dfnew
df$Value <- as.numeric(df$Value)
df<-as.data.frame(df)
df <- subset(df, Outcome %in% c("IncidenceInfectionsGraves"))
df <- subset(df, Reduction %in% c("1","3"))

new_df <- df %>%
  group_by(Scenario,Country, Outcome) %>%
  summarise(Variation = ((Value[Reduction == 3] - Value[Reduction == 1])*100) / Value[Reduction == 1])
df=as.data.frame(new_df)

min_values <- df %>%
  group_by(Country, Outcome) %>%
  summarize(MinValue = min(Variation))

df <- merge(df, min_values, by = c("Country", "Outcome"))

df = df %>% filter(Variation == MinValue)

names(df)[1]="name_long"

# Ajouter les scénarios aux données géospatiales
europe <- europe %>%
  left_join(df, by = "name_long")

# Définir une palette de couleurs pour les scénarios
scenario_colors <- c("1" = "blue", "2" = "green", "3" = "red", "4" = "#FDC257")

# Créer la carte
ggplot(data = europe) +
  geom_sf(aes(fill = Scenario), color = "black") +
  scale_fill_manual(values = scenario_colors, na.value = "grey90") +
  theme_minimal() + theme(axis.text = element_blank(), axis.ticks = element_blank(),panel.grid = element_blank()) +  # Supprimer la grille
  labs(title = "Best Scenario by Country to limit the incidence of severe infections ",
       fill = "Scenario") +
  coord_sf(xlim = c(-10, 30), ylim = c(35, 70), expand = FALSE)


```

