---
title: "CalibrationFi"
output: html_document
date: "2024-07-10"
editor_options: 
  chunk_output_type: console
---

```{r library}


library(ggplot2)
library(tidyr)
library(dplyr)
library(reshape2)
library(ggpubr)
library(socialmixr)
library("RColorBrewer")
library(rmarkdown)
library(plotly)
library(demodelr)
library(forcats)
library(ggh4x)
library(lemon)
library(ggthemes)
library(khroma)
library(here)


```

```{r setup}
#Odin equations 
path <- here::here("Script", "DeuxAgeHuitResistanceDeuxAntibiosOdin.R")
code <- paste(readLines(path, warn = FALSE), collapse = "\n")
gen <- odin::odin(code)


#2021 datas
d2=0.075/0.53; d3=0.075/0.53; d4=0.085/0.53; d5=0.09/0.53; d6=0.12/0.53; d7=0.075/0.53; d8=0.01/0.53 
Rcr=0.58; Rmacro=0.28; Ramox=0.43; pi=0.52
ConsoAmox=0.95; ConsoMacro=0.083;Lambda=1/43
InvasionRate=4.8*10**(-7)


```


```{r optim sur le Ratio de R/R+I+S}

RunSimulation<- function(x) {
    mod <- gen$new(  US_0=c((70000000*(1-(0.0163+0.0016)))*(1-pi)*0.055),
                  UCm1_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  UCm1_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*(Rmacro-Rcr*Ramox)*0.055),
                  UCm2_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d2*0.055),
                  UCm2_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d2*0.055),
                  UCm3_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d3*0.055),
                  UCm3_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d3*0.055),
                  UCm4_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d4*0.055),
                  UCm4_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d4*0.055),
                  UCm5_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d5*0.055),
                  UCm5_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d5*0.055),
                  UCm6_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d6*0.055),
                  UCm6_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d6*0.055),
                  UCm7_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d7*0.055),
                  UCm7_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d7*0.055),
                  UCm8_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d8*0.055),
                  UCm8_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d8*0.055),
                  
                  AES_0=c((70000000*0.0163)*(1-pi)*0.055),
                  AECm1_S_0=c((70000000*0.0163)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  AECm1_R_0=c((70000000*0.0163)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  AECm2_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d2*0.055),
                  AECm2_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d2*0.055),
                  AECm3_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d3*0.055),
                  AECm3_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d3*0.055),
                  AECm4_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d4*0.055),
                  AECm4_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d4*0.055),
                  AECm5_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d5*0.055),
                  AECm5_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d5*0.055),
                  AECm6_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d6*0.055),
                  AECm6_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d6*0.055),
                  AECm7_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d7*0.055),
                  AECm7_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d7*0.055),
                  AECm8_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d8*0.055),
                  AECm8_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d8*0.055),
                  
                  MES_0=c((70000000*0.0016)*(1-pi)*0.055),
                  MECm1_S_0=c((70000000*0.0016)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  MECm1_R_0=c((70000000*0.0016)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  MECm2_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d2*0.055),
                  MECm2_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d2*0.055),
                  MECm3_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d3*0.055),
                  MECm3_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d3*0.055),
                  MECm4_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d4*0.055),
                  MECm4_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d4*0.055),
                  MECm5_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d5*0.055),
                  MECm5_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d5*0.055),
                  MECm6_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d6*0.055),
                  MECm6_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d6*0.055),
                  MECm7_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d7*0.055),
                  MECm7_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d7*0.055),
                  MECm8_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d8*0.055),
                  MECm8_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d8*0.055),
               # Dose1=1 sigmoid 0.08
               fA1=1 ,fA2=x[1] ,fA3=x[2] ,fA4=x[3] ,fA5=x[4],fA6=x[5],fA7=x[6],fA8=x[7],
               fMS=1 ,fMR=x[8],
               
               a1=0,a2=0,a3=0,a4=1,a5=1,a6=1,a7=1,a8=1,
               V=c(x[9]),
               Beta=matrix(c(1),nrow = 1, ncol = 1,byrow = TRUE),
               Phi_A=c(ConsoAmox/365),
               Phi_M=c(ConsoMacro/365),

               Mu=c(0),
               mu0=0,
               Lambda=c(Lambda),
               gamma_A=1/7,
               gamma_M=1/7,
               
               #Dose calculées sur les articles
               dose1_A=1, # MIC=0.06
               dose2_A=0.93,# MIC=0.125
               dose3_A=0.47,#MIC=0.25
               dose4_A=0.06,#MIC=0.5
               dose5_A=0,#MIC=1
               dose6_A=0,# MIC=2
               dose7_A=0, #MIC=4
               dose8_A=0, #MIC=8
               dose1_M= 1.006924, #MIC=0.06
               dose2_M=0.03449561,#MIC=0.125
               
               theta=0.5,
               N_age=1)
    t <- seq(0, 365*5,365)
    y_odin <- mod$run(t)
    out_odin <- as.data.frame(y_odin)
    
    out_odin = out_odin %>%
  mutate(
    `t`=`t`,
    `Cm1S[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`,
    `Cm1R[1]`=`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`,
    `Cm2S[1]`=`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`,
    `Cm2R[1]`=`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`,
    `Cm3S[1]`=`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`,
    `Cm3R[1]`=`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`,
    `Cm4S[1]`=`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`,
    `Cm4R[1]`=`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`,
    `Cm5S[1]`=`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`,
    `Cm5R[1]`=`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`,
    `Cm6S[1]`=`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`,
    `Cm6R[1]`=`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`,
    `Cm7S[1]`=`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`,
    `Cm7R[1]`=`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`,
    `Cm8S[1]`=`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`,
    `Cm8R[1]`=`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,

    `Totcarrier[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
    
    `Tot[1]`=`US[1]`+`AES[1]`+`MES[1]`+`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
    
    .keep = "none"
  )
out_odin = out_odin %>%
  mutate(
    `t`=`t`,
    `Cm1S[1]`=`Cm1S[1]`/`Totcarrier[1]`,
    `Cm1R[1]`=`Cm1R[1]`/`Totcarrier[1]`,
    `Cm2S[1]`=`Cm2S[1]`/`Totcarrier[1]`,
    `Cm2R[1]`=`Cm2R[1]`/`Totcarrier[1]`,
    `Cm3S[1]`=`Cm3S[1]`/`Totcarrier[1]`,
    `Cm3R[1]`=`Cm3R[1]`/`Totcarrier[1]`,
    `Cm4S[1]`=`Cm4S[1]`/`Totcarrier[1]`,
    `Cm4R[1]`=`Cm4R[1]`/`Totcarrier[1]`,
    `Cm5S[1]`=`Cm5S[1]`/`Totcarrier[1]`,
    `Cm5R[1]`=`Cm5R[1]`/`Totcarrier[1]`,
    `Cm6S[1]`=`Cm6S[1]`/`Totcarrier[1]`,
    `Cm6R[1]`=`Cm6R[1]`/`Totcarrier[1]`,
    `Cm7S[1]`=`Cm7S[1]`/`Totcarrier[1]`,
    `Cm7R[1]`=`Cm7R[1]`/`Totcarrier[1]`,
    `Cm8S[1]`=`Cm8S[1]`/`Totcarrier[1]`,
    `Cm8R[1]`=`Cm8R[1]`/`Totcarrier[1]`,
    `Totcarrier[1]`=`Totcarrier[1]`/`Tot[1]`,
    .keep = "none"
  )
    
     return(out_odin)

}


datasDistributions2021<-c((1-Rmacro)-(1-Rcr)*Ramox,Rmacro-Rcr*Ramox,(1-Rcr)*Ramox*d2,Rcr*Ramox*d2,(1-Rcr)*Ramox*d3,Rcr*Ramox*d3,(1-Rcr)*Ramox*d4,
                          Rcr*Ramox*d4,(1-Rcr)*Ramox*d5,Rcr*Ramox*d5,(1-Rcr)*Ramox*d6,Rcr*Ramox*d6,(1-Rcr)*Ramox*d7,
                          Rcr*Ramox*d7,(1-Rcr)*Ramox*d8,Rcr*Ramox*d8,pi)


datasDistributions<-as.data.frame(
  matrix(rep(datasDistributions2021, times = 6),
         nrow=6,byrow=TRUE))


mLL_gauss <- function(param, obs_df=datasDistributions) {
  
  predictions <- RunSimulation(param) # solve function solve with parameters on the param list
  #predictions <-predictions[-1,]
  
  pred_df <- predictions %>% 
    select(`Cm1S[1]`:`Totcarrier[1]`)%>%#keep only the variable of interest to compare to data
    mutate_all(as.numeric)   

  pred_mat <- as.matrix(pred_df)
   
  obs_mat  <- as.matrix(obs_df)
  
  #calcul de la vraissmeblance de la prévalence
  
  ll_mat <- dnorm(x = pred_mat,
                  mean = obs_mat,
                  sd=0.05,
                  log    = TRUE)
  neg_logL <- -sum(ll_mat, na.rm = TRUE)
  
  return(neg_logL)
}

x0=c(0.99,0.98,0.93,0.9,0.9,0.8,0.8,0.95,0.01)

mLL_gauss(x0)


res_TransmissibilityParameters <- data.frame()

set.seed(123)
for (i in 1:1) {
  set.seed(i)

  # tirage aléatoire du point de départ (9 paramètres)
  x0 <- c(
    runif(8, min = 0.8, max = 0.9),   # fACMI2..fACMI8 + fMR (8 parameters)
    runif(1, min = 0.001, max = 0.1)  # Beta
  )

  fit <- optim(par = x0,fn = mLL_gauss,method = "L-BFGS-B",lower = c(0.8,0.8,0.8, 0.8,0.8,0.8,0.8,0.95,0.001),upper=c(1,1,1,1,1,1,1,1,0.1) )

  fACMI2 <- fit$par[1]
  fACMI3 <- fit$par[2]
  fACMI4 <- fit$par[3]
  fACMI5 <- fit$par[4]
  fACMI6 <- fit$par[5]
  fACMI7 <- fit$par[6]
  fACMI8 <- fit$par[7]
  fMR    <- fit$par[8]
  Beta   <- fit$par[9]

  res_TransmissibilityParameters <- rbind(
    res_TransmissibilityParameters,
    data.frame(
      seed = i,
      fACMI2 = fACMI2,
      fACMI3 = fACMI3,
      fACMI4 = fACMI4,
      fACMI5 = fACMI5,
      fACMI6 = fACMI6,
      fACMI7 = fACMI7,
      fACMI8 = fACMI8,
      fMR    = fMR,
      Beta   = Beta,
      negLogLik = fit$value,
      convergence = fit$convergence
    )
  )
}

res_TransmissibilityParameters

mean_params <- colMeans(
  res_TransmissibilityParameters[, c("fACMI2","fACMI3","fACMI4","fACMI5","fACMI6","fACMI7","fACMI8","fMR","Beta")],
  na.rm = TRUE
)

print(mean_params)


```



