---
title: "PRCCAnlaysis_Figure4"
output: html_document
date: "2024-07-10"
editor_options: 
  chunk_output_type: console
---

```{r library}
library(ggplot2)
library(readxl)
library(tidyr)
library(dplyr)
library(reshape2)
library(ggpubr)
library(socialmixr)
data(polymod)
library("RColorBrewer")
library(rmarkdown)
library(plotly)
library(demodelr)
library(forcats)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(corrplot)
library(gridExtra)
library(gridGraphics)
library(grid)
library(patchwork)
library(refset)
library("cowplot")
library(lhs)

```


```{r setup}

#Odin equations 
path <- here::here("Script", "DeuxAgeHuitResistanceDeuxAntibiosOdin.R")
code <- paste(readLines(path, warn = FALSE), collapse = "\n")
gen <- odin::odin(code)

#Donnes 2021 otites pour penicillines: 
d2=0.075/0.53; d3=0.075/0.53; d4=0.085/0.53; d5=0.09/0.53; d6=0.12/0.53; d7=0.075/0.53; d8=0.01/0.53 
Rcr=0.58; Rmacro=0.28; Ramox=0.43; pi=0.52
InvasionRate=4.8*10**(-7)

```



```{r optim Vi on carriage rate}

OptimVi <- function(x,param) {
  Rcr=as.numeric(param[1])
  Ramox=as.numeric(param[2])
  Rmacro=as.numeric(param[3])
  ConsoAmox=as.numeric(param[4])
  ConsoMacro=as.numeric(param[5])
  pi=as.numeric(param[6])
  Lambda=as.numeric(param[7])
  TreatmentDuration_Amox=as.numeric(param[8])
  TreatmentDuration_Macro=as.numeric(param[9])
  mod <- gen$new( US_0=c((70000000*(1-(0.0163+0.0016)))*(1-pi)*0.055),
                  UCm1_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  UCm1_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*(Rmacro-Rcr*Ramox)*0.055),
                  UCm2_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d2*0.055),
                  UCm2_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d2*0.055),
                  UCm3_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d3*0.055),
                  UCm3_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d3*0.055),
                  UCm4_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d4*0.055),
                  UCm4_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d4*0.055),
                  UCm5_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d5*0.055),
                  UCm5_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d5*0.055),
                  UCm6_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d6*0.055),
                  UCm6_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d6*0.055),
                  UCm7_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d7*0.055),
                  UCm7_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d7*0.055),
                  UCm8_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d8*0.055),
                  UCm8_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d8*0.055),
                  
                  AES_0=c((70000000*0.0163)*(1-pi)*0.055),
                  AECm1_S_0=c((70000000*0.0163)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  AECm1_R_0=c((70000000*0.0163)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  AECm2_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d2*0.055),
                  AECm2_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d2*0.055),
                  AECm3_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d3*0.055),
                  AECm3_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d3*0.055),
                  AECm4_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d4*0.055),
                  AECm4_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d4*0.055),
                  AECm5_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d5*0.055),
                  AECm5_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d5*0.055),
                  AECm6_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d6*0.055),
                  AECm6_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d6*0.055),
                  AECm7_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d7*0.055),
                  AECm7_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d7*0.055),
                  AECm8_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d8*0.055),
                  AECm8_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d8*0.055),
                  
                  MES_0=c((70000000*0.0016)*(1-pi)*0.055),
                  MECm1_S_0=c((70000000*0.0016)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  MECm1_R_0=c((70000000*0.0016)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  MECm2_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d2*0.055),
                  MECm2_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d2*0.055),
                  MECm3_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d3*0.055),
                  MECm3_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d3*0.055),
                  MECm4_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d4*0.055),
                  MECm4_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d4*0.055),
                  MECm5_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d5*0.055),
                  MECm5_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d5*0.055),
                  MECm6_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d6*0.055),
                  MECm6_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d6*0.055),
                  MECm7_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d7*0.055),
                  MECm7_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d7*0.055),
                  MECm8_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d8*0.055),
                  MECm8_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d8*0.055),
                  
                  # Fitness cost
                  fA1=1, fA2=0.9999748 , fA3=0.9916096 , fA4=0.9420954 , fA5=0.9192299 , fA6=0.9192278 , fA7=0.9192375 , fA8=0.9194097 ,
                  fMS=1,fMR=0.9938509 ,
                  a1=0,a2=0,a3=0,a4=1,a5=1,a6=1,a7=1,a8=1,
                  V=c(x[1]),
                  
                  Beta=matrix(c(1),nrow = 1, ncol = 1,byrow = TRUE),
                  
                  #Consommation normale observée
                  Phi_A=c(ConsoAmox/365),
                  Phi_M=c(ConsoMacro/365),
                  
                  Mu=c(0),  #c((0.76*10**(-3))/365,(0.1*10**(-3))/365,(2.16*10**(-3))/365,(50*10**(-3))/365),
                  mu0=0,
                  Lambda=c(Lambda),
                  gamma_A=1/TreatmentDuration_Amox,
                  gamma_M=1/TreatmentDuration_Macro,
                  
                  #Dose calculées sur les articles
                  dose1_A= 1, #500mg,q12h MIC=0.06
                  dose2_A=0.93,#500mg,q12h MIC=0.125
                  dose3_A=0.47,#500mg,q12h MIC=0.25
                  dose4_A=0.06,#500mg,q12h MIC=0.5
                  dose5_A=0,#500mg,q12h MIC=1
                  dose6_A=0,#500mg,q12h MIC=2
                  dose7_A=0, #500mg,q12h MIC=4
                  dose8_A=0, #500mg,q8h MIC=8
                  dose1_M= 1.006924, #500mg,q12h MIC=0.06
                  dose2_M=0.03449561,#500mg,q12h MIC=0.125
                  
                  theta=0.5,
                  N_age=1)
  
  t <- seq(0, 365*1,0.1)
  y_odin <- mod$run(t)
  out_odin <- as.data.frame(y_odin)
  
  out_odin=out_odin[c(nrow(out_odin)),]
  
  out_odin = out_odin %>%
    mutate(
      `t`=`t`,
      `Totcarrier[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
      
      `Tot[1]`=`US[1]`+`AES[1]`+`MES[1]`+`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
      
      .keep = "none"
    )
  out_odin = out_odin %>%
    mutate(
      `t`=`t`,
      `Totcarrier[1]`=`Totcarrier[1]`/`Tot[1]`,
      .keep = "none"
    )
  
  f=out_odin
  
  p1=as.numeric(f[2])
  
  #cat(x[1],"",x[2], "",x[3], "",x[4])
  
  return(abs(pi-p1)**2)
}


```


```{r lancement}

RunShortage9param<-function(param){
  df<-data.frame(Scenario=numeric(), Reduction=numeric(), Outcome=character(), Value=numeric())
  Rcr=as.numeric(param[1])
  Ramox=as.numeric(param[2])
  Rmacro=as.numeric(param[3])
  ConsoAmox=as.numeric(param[4])
  ConsoMacro=as.numeric(param[5])
  pi=as.numeric(param[6])
  Lambda=as.numeric(param[7])
  TreatmentDuration_Amox=as.numeric(param[8])
  TreatmentDuration_Macro=as.numeric(param[9])
  
  Vopti=as.numeric((Optim_vi=optim(c(0.01),OptimVi,param=param,control = list(maxit = 20000)))$par)
  print(Vopti)
  for (k in 1:4){
    #print(k)
    if(k==1){ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(1,1,1,1)
    ReductionFreq=c(1,0.75,0.5,0.25)
    AugmentationFreq=c(0,0,0,0)
    A=matrix(c(0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)
     }
     
     if(k==2){ ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(1,0.75,0.5,0.25)
    ReductionFreq=c(1,1,1,1)
    AugmentationFreq=c(0,0,0,0)
    A=matrix(c(0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)
     }
     
    if(k==3){ ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.06,0,0,0,0,0,
          1,0.47,0,0,0,0,0,0,
          1,0.06,0,0,0,0,0,0),ncol=4)
    ReductionDuree=c(1,1,1,1)
    ReductionFreq=c(1,1,1,1)
    AugmentationFreq=c(0,0,0,0)
     A=matrix(c(0,0,0,1,1,1,1,1,
               0,0,1,1,1,1,1,1,
               0,0,1,1,1,1,1,1,
               0,1,1,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)
    }
    if(k==4){ReductionDose=matrix(c(1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0,
          1,0.93,0.47,0.06,0,0,0,0),ncol=4)
    ReductionDuree=c(1,1,1,1)
    ReductionFreq=c(1,0.75,0.5,0.25)
    AugmentationFreq=c(0,0.25,0.5,0.75)
    A=matrix(c(0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1),nrow =4 ,ncol=8,byrow = TRUE)}
    
    for(j in 1:4){
      #print(j)
      mod <- gen$new( US_0=c((70000000*(1-(0.0163+0.0016)))*(1-pi)*0.055),
                  UCm1_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  UCm1_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*(Rmacro-Rcr*Ramox)*0.055),
                  UCm2_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d2*0.055),
                  UCm2_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d2*0.055),
                  UCm3_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d3*0.055),
                  UCm3_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d3*0.055),
                  UCm4_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d4*0.055),
                  UCm4_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d4*0.055),
                  UCm5_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d5*0.055),
                  UCm5_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d5*0.055),
                  UCm6_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d6*0.055),
                  UCm6_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d6*0.055),
                  UCm7_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d7*0.055),
                  UCm7_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d7*0.055),
                  UCm8_S_0=c((70000000*(1-(0.0163+0.0016)))*pi*(1-Rcr)*Ramox*d8*0.055),
                  UCm8_R_0=c((70000000*(1-(0.0163+0.0016)))*pi*Rcr*Ramox*d8*0.055),
                  
                  AES_0=c((70000000*0.0163)*(1-pi)*0.055),
                  AECm1_S_0=c((70000000*0.0163)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  AECm1_R_0=c((70000000*0.0163)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  AECm2_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d2*0.055),
                  AECm2_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d2*0.055),
                  AECm3_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d3*0.055),
                  AECm3_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d3*0.055),
                  AECm4_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d4*0.055),
                  AECm4_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d4*0.055),
                  AECm5_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d5*0.055),
                  AECm5_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d5*0.055),
                  AECm6_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d6*0.055),
                  AECm6_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d6*0.055),
                  AECm7_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d7*0.055),
                  AECm7_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d7*0.055),
                  AECm8_S_0=c((70000000*0.0163)*pi*(1-Rcr)*Ramox*d8*0.055),
                  AECm8_R_0=c((70000000*0.0163)*pi*Rcr*Ramox*d8*0.055),
                  
                  MES_0=c((70000000*0.0016)*(1-pi)*0.055),
                  MECm1_S_0=c((70000000*0.0016)*pi*((1-Rmacro)-(1-Rcr)*Ramox)*0.055),
                  MECm1_R_0=c((70000000*0.0016)*pi*(Rmacro-Rcr*Ramox)*0.055),
                  MECm2_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d2*0.055),
                  MECm2_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d2*0.055),
                  MECm3_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d3*0.055),
                  MECm3_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d3*0.055),
                  MECm4_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d4*0.055),
                  MECm4_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d4*0.055),
                  MECm5_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d5*0.055),
                  MECm5_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d5*0.055),
                  MECm6_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d6*0.055),
                  MECm6_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d6*0.055),
                  MECm7_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d7*0.055),
                  MECm7_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d7*0.055),
                  MECm8_S_0=c((70000000*0.0016)*pi*(1-Rcr)*Ramox*d8*0.055),
                  MECm8_R_0=c((70000000*0.0016)*pi*Rcr*Ramox*d8*0.055),
                      
                   fA1=1, fA2=0.9999748 , fA3=0.9916096 , fA4=0.9420954 , fA5=0.9192299 , fA6=0.9192278 , fA7=0.9192375 , fA8=0.9194097 ,
                  fMS=1,fMR=0.9938509 ,
                  a1=A[j,1],a2=A[j,2],a3=A[j,3],a4=A[j,4],a5=A[j,5],a6=A[j,6],a7=A[j,7],a8=A[j,8],
                  V=c(Vopti),
                      
                  Beta=matrix(c(1),nrow = 1, ncol = 1,byrow = TRUE),
                      
                      #Consommation normale observée
                      Phi_A=c(ConsoAmox*ReductionFreq[j]/(365)),
                      
                      Phi_M=c((ConsoMacro*(1+((ConsoAmox)/(ConsoMacro))*AugmentationFreq[j]))/365),
                      
                      Mu=c(0),  #c((0.76*10**(-3))/365,(0.1*10**(-3))/365,(2.16*10**(-3))/365,(50*10**(-3))/365),
                      mu0=0,
                      Lambda=c(Lambda),
                      gamma_A=1/(TreatmentDuration_Amox*ReductionDuree[j]),
                      gamma_M=1/(TreatmentDuration_Macro),
                      
                      #Dose 500mg, q8h
                      dose1_A=ReductionDose[1,j],
                      dose2_A=ReductionDose[2,j],
                      dose3_A=ReductionDose[3,j],
                      dose4_A=ReductionDose[4,j],
                      dose5_A=ReductionDose[5,j],
                      dose6_A=ReductionDose[6,j],
                      dose7_A=ReductionDose[7,j],
                      dose8_A=ReductionDose[8,j],
                      dose1_M= 1.006924, #500mg,q12h MIC=0.06
                      dose2_M=0.03449561,#500mg,q12h MIC=0.125
                      
                      theta=0.5,
                      N_age=1)
      
      t <- seq(0, 365*1,1)
      y_odin <- mod$run(t)
      out_odin <- as.data.frame(y_odin)
      out_odin = out_odin %>%
        mutate(
          `t`=`t`,
          `S[1]`=`US[1]`+`AES[1]`+`MES[1]`,
          `Cm1[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`,
          `Cm2[1]`=`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`,
          `Cm3[1]`=`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`,
          `Cm4[1]`=`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`,
          `Cm5[1]`=`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`,
          `Cm6[1]`=`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`,
          `Cm7[1]`=`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`,
          `Cm8[1]`=`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          `CmS[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`,
          `CmR[1]`=`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          `CmNsR[1]`=`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          `Totcarrier[1]`=`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          `Tot[1]`=`US[1]`+`AES[1]`+`MES[1]`+`UCm1_S[1]`+`AECm1_S[1]`+`MECm1_S[1]`+`UCm1_R[1]`+`AECm1_R[1]`+`MECm1_R[1]`+`UCm2_S[1]`+`AECm2_S[1]`+`MECm2_S[1]`+`UCm2_R[1]`+`AECm2_R[1]`+`MECm2_R[1]`+`UCm3_S[1]`+`AECm3_S[1]`+`MECm3_S[1]`+`UCm3_R[1]`+`AECm3_R[1]`+`MECm3_R[1]`+`UCm4_S[1]`+`AECm4_S[1]`+`MECm4_S[1]`+`UCm4_R[1]`+`AECm4_R[1]`+`MECm4_R[1]`+`UCm5_S[1]`+`AECm5_S[1]`+`MECm5_S[1]`+`UCm5_R[1]`+`AECm5_R[1]`+`MECm5_R[1]`+`UCm6_S[1]`+`AECm6_S[1]`+`MECm6_S[1]`+`UCm6_R[1]`+`AECm6_R[1]`+`MECm6_R[1]`+`UCm7_S[1]`+`AECm7_S[1]`+`MECm7_S[1]`+`UCm7_R[1]`+`AECm7_R[1]`+`MECm7_R[1]`+`UCm8_S[1]`+`AECm8_S[1]`+`MECm8_S[1]`+`UCm8_R[1]`+`AECm8_R[1]`+`MECm8_R[1]`,
          
          .keep = "none"
        )
      out_odin = out_odin %>%
      mutate(
        `InfectionsGraves[1]`=InvasionRate*`Totcarrier[1]`,
        `InfectionsGravesPNSP[1]`=InvasionRate*(`Cm2[1]`+`Cm3[1]`+`Cm4[1]`+`Cm5[1]`+`Cm6[1]`+`Cm7[1]`+`Cm8[1]`),
        `InfectionsGravesMR[1]`=InvasionRate*`CmR[1]`,
        `InfectionsGravesPNSPMR[1]`=InvasionRate*`CmNsR[1]`,
        )
    
    out_odin = out_odin %>%
      mutate(
        `InfectionsGravesCumulees[1]`=cumsum(`InfectionsGraves[1]`),
        `InfectionsGravesPNSPCumulees[1]`=cumsum(`InfectionsGravesPNSP[1]`),
        `InfectionsGravesMRCumulees[1]`=cumsum(`InfectionsGravesMR[1]`),
        `InfectionsGravesPNSPMRCumulees[1]`=cumsum(`InfectionsGravesPNSPMR[1]`),
        )
    
    out_odin=out_odin[c(nrow(out_odin)),]
    
    As1<-(out_odin$`Cm1[1]`)/(out_odin$`Totcarrier[1]`) 
    
    Ans1=1-As1
    
    Ms1<-(out_odin$`CmS[1]`)/(out_odin$`Totcarrier[1]`)
    
    Mr1<-(out_odin$`CmR[1]`)/(out_odin$`Totcarrier[1]`)
    
    AnsMr1<-(out_odin$`CmNsR[1]`)/(out_odin$`Totcarrier[1]`)
    
    I1<-out_odin$`InfectionsGravesCumulees[1]`*100000/(70000000*0.055)
    
    IAns1<-out_odin$`InfectionsGravesPNSPCumulees[1]`*100000/(70000000*0.055)
    
    IMr1<-out_odin$`InfectionsGravesMRCumulees[1]`*100000/(70000000*0.055)
    
    IAnsMr1<-out_odin$`InfectionsGravesPNSPMRCumulees[1]`*100000/(70000000*0.055)
      
      outputAns=Ans1
      outputMr=Mr1
      outputAnsMr=AnsMr1
      
      outputIgrave=I1
      outputIgraveAns=IAns1
      outputIgraveMr=IMr1
      outputIgraveAnsMr=IAnsMr1
      
      df2<-data.frame(Scenario=numeric(), Reduction=numeric(), Outcome=character(), Value=numeric() )
      df2[1,]<-c(k,j,"PropAns",outputAns)
      df2[2,]<-c(k,j,"PropMr",outputMr)
      df2[3,]<-c(k,j,"PropAnsMr",outputAnsMr)
      df2[4,]<-c(k,j,"IncidenceInfectionsGraves",outputIgrave)
      df2[5,]<-c(k,j,"IncidenceInfectionsGravesAns",outputIgraveAns)
      df2[6,]<-c(k,j,"IncidenceInfectionsGravesMr",outputIgraveMr)
      df2[7,]<-c(k,j,"IncidenceInfectionsGravesAnsMr",outputIgraveAnsMr)
      df=rbind(df,df2)
    }
  }
  
    df <- subset(df, Reduction %in% c("1","3"))
    df$Value <- as.numeric(df$Value)
    
    summary_stats <- df %>% 
    group_by(Outcome, Scenario) %>%
    summarize(
      Variation = (abs(Value[Reduction == 3] - Value[Reduction == 1])*100) / Value[Reduction == 1])
    
    df=as.data.frame(summary_stats)
    #print(df)
     #Toute les sorties du modèle qui nous intéressent pour l'anlayse de senisbilité
    
    outIgS1<-as.numeric(subset(df, Outcome=="IncidenceInfectionsGraves"& Scenario==1)$Variation)
    outIgS2<-as.numeric(subset(df, Outcome=="IncidenceInfectionsGraves"& Scenario==2)$Variation)
    outIgS3<-as.numeric(subset(df, Outcome=="IncidenceInfectionsGraves"& Scenario==3)$Variation)
    outIgS4<-as.numeric(subset(df, Outcome=="IncidenceInfectionsGraves"& Scenario==4)$Variation)

    outPropAnsS1<-as.numeric(subset(df, Outcome=="PropAns"& Scenario==1)$Variation)
    outPropAnsS2<-as.numeric(subset(df, Outcome=="PropAns"& Scenario==2)$Variation)
    outPropAnsS3<-as.numeric(subset(df, Outcome=="PropAns"& Scenario==3)$Variation)
    outPropAnsS4<-as.numeric(subset(df, Outcome=="PropAns"& Scenario==4)$Variation)

    outPropMrS1<-as.numeric(subset(df, Outcome=="PropMr"& Scenario==1)$Variation)
    outPropMrS2<-as.numeric(subset(df, Outcome=="PropMr"& Scenario==2)$Variation)
    outPropMrS3<-as.numeric(subset(df, Outcome=="PropMr"& Scenario==3)$Variation)
    outPropMrS4<-as.numeric(subset(df, Outcome=="PropMr"& Scenario==4)$Variation)

    outPropAnsMrS1<-as.numeric(subset(df, Outcome=="PropAnsMr"& Scenario==1)$Variation)
    outPropAnsMrS2<-as.numeric(subset(df, Outcome=="PropAnsMr"& Scenario==2)$Variation)
    outPropAnsMrS3<-as.numeric(subset(df, Outcome=="PropAnsMr"& Scenario==3)$Variation)
    outPropAnsMrS4<-as.numeric(subset(df, Outcome=="PropAnsMr"& Scenario==4)$Variation)

    out<-c(outIgS1,outIgS2,outIgS3,outIgS4,outPropAnsS1,outPropAnsS2,outPropAnsS3,outPropAnsS4,outPropMrS1,outPropMrS2,outPropMrS3,outPropMrS4,outPropAnsMrS1,outPropAnsMrS2,outPropAnsMrS3,outPropAnsMrS4)
    
    return(out)
  
}

#dfw<-RunShortage9param(c(0.58,0.43,0.28,0.95,0.083,0.52,43,7,7))

#dfw<-RunShortage9param(c(0.5313937,0.4684631,0.2823471,0.9690644,0.08296454,0.5363854,43.63831,6.068079,6.402729))

```



```{r set randomLHS}
set.seed(118)


var=0.05
parametres_list <- list(
  Rcr=c(0.58,var*0.58), 
  Ramox=c(0.43,var*0.43),
  Rmacro=c(0.28,var*0.28),
  ConsoAmox=c(0.95,var*0.95),
  ConsoMacro=c(0.083,var*0.083),
  pi=c(0.52,var*0.52),
  LambdaAge=c(1/43,var*(1/43)),
  TreatmentDuration_Amox=c(7,var*7),
  TreatmentDuration_Macro=c(7,var*7))


# Définir le nombre d'itérations de LHS
nb_lhs_iterations <- 500

# Fonction pour générer un échantillon avec LHS pour les paramètres Lambda
genere_echantillon_lhs_lambda <- function(parametres, n) {
  lhs_sample <- randomLHS(n = n, k = length(parametres))
  echantillon <- matrix(NA, nrow = n, ncol = length(parametres))
  for (i in seq_along(parametres)) {
    print(parametres[[i]][1])
    echantillon[, i] <- qnorm(lhs_sample[, i],parametres[[i]][1] ,parametres[[i]][2])
  }
  return(echantillon)
}

# Exécuter LHS pour générer un échantillon pour les paramètres Lambda
resultats_lhs <- genere_echantillon_lhs_lambda(parametres_list, nb_lhs_iterations)
resultats_lhs=as.data.frame(resultats_lhs)


#Génerer les resultats du modèle pour chaque échantillon

resultats <- t(apply(resultats_lhs, 1, RunShortage9param)) #dataframe de nb_lhs_iterations lignes et de 16 colonnes respectivement : outIgS1,outIgS2,outIgS3,outIgS4,outPropAnsS1,outPropAnsS2,outPropAnsS3,outPropAnsS4,outPropMRS1,outPropMRS2,outPropMRS3,outPropMRS4,outPropRcrS1,outPropRcrS, outPropRcrS3,outPropRcrS4

#write.csv(resultats,"Files\\ResultsRCCN500_abs.csv")



#Ouvrir fichier Resultats
resultats<-read.csv("Files\\ResultsRCCN500_abs.csv")
resultats<-subset(resultats, select = -X)

outIgS1<-as.numeric(resultats[,1])
outIgS2<-as.numeric(resultats[,2])
outIgS3<-as.numeric(resultats[,3])
outIgS4<-as.numeric(resultats[,4])

outPropAnsS1<-as.numeric(resultats[,5])
outPropAnsS2<-as.numeric(resultats[,6])
outPropAnsS3<-as.numeric(resultats[,7])
outPropAnsS4<-as.numeric(resultats[,8])

outPropMrS1<-as.numeric(resultats[,9])
outPropMrS2<-as.numeric(resultats[,10])
outPropMrS3<-as.numeric(resultats[,11])
outPropMrS4<-as.numeric(resultats[,12])

outPropAnsMrS1<-as.numeric(resultats[,13])
outPropAnsMrS2<-as.numeric(resultats[,14])
outPropAnsMrS3<-as.numeric(resultats[,15])
outPropAnsMrS4<-as.numeric(resultats[,16])

# Préparer les données pour l'analyse PCC
param_names <- c("Rcr", "Ramox", "Rmacro", "ConsoAmox", "ConsoMacro","pi", "LambdaAge", "TreatmentDuration_Amox", "TreatmentDuration_Macro")
colnames(resultats_lhs) <- param_names


# res<-pcc(X = resultats_lhs,semi=TRUE, y = outIgS1, nboot=200)
# res$"SPCC"$original[1]

#Creer dataframe avec outcomes


creerDataframePRCC<-function(outcome,scenario){
  dataframe_name <- sprintf("out%sS%d", outcome, scenario) #récupère le nom de l'outcome et du scénario, et prend la valeur du vecteur défini plus haut ( ex : outPropAnsMrS1)
  res<-pcc(X = resultats_lhs,rank = TRUE,semi=FALSE,y = get(dataframe_name), nboot=20)
  data1<-data.frame(Scenario=numeric(),Outcome=character(),Variable=character(),Moyenne=numeric(), Ecart_type=numeric() )
  data1[1,]<-c(scenario,outcome,"Rcr",res$PRCC$original[1],res$PRCC$`std. error`[1])
  data1[2,]<-c(scenario,outcome,"Ramox",res$PRCC$original[2],res$PRCC$`std. error`[2])
  data1[3,]<-c(scenario,outcome,"Rmacro",res$PRCC$original[3],res$PRCC$`std. error`[3])
  data1[4,]<-c(scenario,outcome,"ConsoAmox",res$PRCC$original[4],res$PRCC$`std. error`[4])
  data1[5,]<-c(scenario,outcome,"ConsoMacro",res$PRCC$original[5],res$PRCC$`std. error`[5])
  data1[6,]<-c(scenario,outcome,"pi",res$PRCC$original[6],res$PRCC$`std. error`[6])
  data1[7,]<-c(scenario,outcome,"LambdaAge",res$PRCC$original[7],res$PRCC$`std. error`[7])
  data1[8,]<-c(scenario,outcome,"TreatmentDuration_Amox",res$PRCC$original[8],res$PRCC$`std. error`[8])
  data1[9,]<-c(scenario,outcome,"TreatmentDuration_Macro",res$PRCC$original[9],res$PRCC$`std. error`[9])
  return(data1)
}


dfRCC<-data.frame(Scenario=numeric(),Outcome=character(),Variable=character(),Moyenne=numeric(), Ecart_type=numeric() )

for(i in ListeOutcome<-c("Ig","PropAns","PropMr","PropAnsMr")){
  for(j in 1:4){
    dfout<-creerDataframePRCC(i,j)
    dfRCC<-rbind(dfRCC,dfout)
  }
}

write.csv(dfRCC,"Files\\DataframePRCCN500_abs.csv")




```


```{r lire et combiner RDS files plot heatmap Abs}

#Ouvrir fichier Resultats

resultats_PartialRankCorrelationCoefficients<-read.csv("Files\\DataframePRCCN500_abs.csv")

df<-subset(resultats_PartialRankCorrelationCoefficients, select = -X)
df$Moyenne <- as.numeric(df$Moyenne)
df$Ecart_type <- as.numeric(df$Ecart_type)


df$Variable <- factor(df$Variable, levels = c( "Rcr","Ramox", "Rmacro", "ConsoAmox", "ConsoMacro", "pi", "LambdaAge", "TreatmentDuration_Amox", "TreatmentDuration_Macro"))
df <- df[order(df$Variable), ]

df$Outcome <- factor(df$Outcome, levels = c("PropAns","PropMr","PropAnsMr","Ig"))
df <- df[order(df$Outcome), ]

df$Scenario <- factor(df$Scenario, levels = c(4, 3, 2, 1))
df <- df[order(df$Scenario), ]

# df <- subset(df, Outcome %in% c("PropAns"))
# df <- subset(df, Scenario %in% c("1"))


variableOutcome_name<-c("PropAns"="Penicillin-non-susceptible strains","PropMr"="Macrolide-resistant strains","PropAnsMr"="Multidrug-resistant strains","Ig"="Invasive pneumococcal disease")

ggAbs<-ggplot(df, aes(x = Variable, y = Scenario, fill = Moyenne)) +
  geom_tile() +
  geom_text(aes(label = sprintf("%.2f", round(Moyenne,digits=2))),show.legend = TRUE) +
  scale_fill_gradient2(low = "#075AFF",mid="white", high = "#FF6347",name = "PRCC") +  # Choix des couleurs
  facet_wrap(~Outcome,labeller = labeller(Outcome=variableOutcome_name))+
  scale_y_discrete(labels = c("S4", "S3", "S2","S1"))+
  scale_x_discrete(labels = c(bquote(~Rcr^'init'), bquote(~PNSP^'init'),bquote(~MR^'init'), expression(Phi[Amox]), expression(Phi[Macro]),bquote(~'pi'^'init'), expression(lambda), expression(gamma[Amox]), expression(gamma[Macro])))+
  theme_bw()+labs(x = NULL, y = NULL)+
  theme(axis.text = element_text(size = 14),axis.title = element_text(size = 12),
        legend.title=element_text(size = 12),legend.text=element_text(size = 12),
        legend.key.height = unit(0.7, "cm"),legend.key.width = unit(0.7, "cm"),
        strip.text = element_text(size = 16, face = "bold",hjust = 0.5),
        strip.background = element_rect(fill = "white"), panel.border =element_rect(colour = "black", fill = NA, size = 1.5),
        plot.background = element_blank())


```

```{r lire et combiner RDS files plot heatmap NoAbs}

#Ouvrir fichier Resultats

resultats_PartialRankCorrelationCoefficients<-read.csv("Files\\DataframePRCCN500_noabs.csv")

df<-subset(resultats_PartialRankCorrelationCoefficients, select = -X)
df$Moyenne <- as.numeric(df$Moyenne)
df$Ecart_type <- as.numeric(df$Ecart_type)


df$Variable <- factor(df$Variable, levels = c( "Rcr","Ramox", "Rmacro", "ConsoAmox", "ConsoMacro", "pi", "LambdaAge", "TreatmentDuration_Amox", "TreatmentDuration_Macro"))
df <- df[order(df$Variable), ]

df$Outcome <- factor(df$Outcome, levels = c("PropAns","PropMr","PropAnsMr","Ig"))
df <- df[order(df$Outcome), ]

df$Scenario <- factor(df$Scenario, levels = c(4, 3, 2, 1))
df <- df[order(df$Scenario), ]

# df <- subset(df, Outcome %in% c("PropAns"))
# df <- subset(df, Scenario %in% c("1"))


variableOutcome_name<-c("PropAns"="Penicillin-non-susceptible strains","PropMr"="Macrolide-resistant strains","PropAnsMr"="Multidrug-resistant strains","Ig"="Invasive pneumococcal disease")

ggNoAbs<-ggplot(df, aes(x = Variable, y = Scenario, fill = Moyenne)) +
  geom_tile() +
  geom_text(aes(label = sprintf("%.2f", round(Moyenne,digits=2))),show.legend = TRUE) +
  scale_fill_gradient2(low = "#075AFF",mid="white", high = "#FF6347",name = "PRCC") +  # Choix des couleurs
  facet_wrap(~Outcome,labeller = labeller(Outcome=variableOutcome_name))+
  scale_y_discrete(labels = c("S4", "S3", "S2","S1"))+
  scale_x_discrete(labels = c(bquote(~Rcr^'init'), bquote(~PNSP^'init'),bquote(~MR^'init'), expression(Phi[Amox]), expression(Phi[Macro]),bquote(~'pi'^'init'), expression(lambda), expression(gamma[Amox]), expression(gamma[Macro])))+
  theme_bw()+labs(x = NULL, y = NULL)+
  theme(axis.text = element_text(size = 14),axis.title = element_text(size = 12),
        legend.title=element_text(size = 12),legend.text=element_text(size = 12),
        legend.key.height = unit(0.7, "cm"),legend.key.width = unit(0.7, "cm"),
        strip.text = element_text(size = 16, face = "bold",hjust = 0.5),
        strip.background = element_rect(fill = "white"), panel.border =element_rect(colour = "black", fill = NA, size = 1.5),
        plot.background = element_blank())



```


```{r grid arrange}

pdf("Figures\\FigureSupplementary4_PRCC.pdf", width = 1200/81, height = 1200/81)

#grid.arrange(gproportion,gIPD,ncol=1)
plot_grid(ggNoAbs,ggAbs,labels=c("a","b"),ncol=1,label_size = 30,rel_heights = c(1, 1))

 # Fermer le périphérique graphique
dev.off()

```


